// Seed dataset for iAtomica CRM & Jira Suite - Valencia 2026
// Sourced from commercial prospecting dataset in Valencia (Cabanyal, Marítim, Serrería)
// Linked to Stefi Del Papa (Project Lead · España) and Lic. Mateo Rossi (Admin)

export const initialValenciaCompanies = [
  {
    "id": "vlc-1",
    "name": "OSB Arquitectos",
    "legalName": "OSB Arquitectos S.L.",
    "industry": "Arquitectura & Diseño",
    "contactName": "Dirección de Estudio OSB",
    "contactRole": "Arquitecto Titular",
    "email": "contacto@osbarquitectos.com",
    "phone": "+34 963 20 40 85",
    "website": "https://osbarquitectos.com",
    "status": "lead",
    "estimatedValue": 2400,
    "assignedTo": "Lic. Mateo Rossi",
    "techRequirements": "Modernización estética de sitio web, portfolio visual de proyectos en alta resolución y sistema automatizado de cotizaciones.",
    "notes": "Dirección: Carrer d'Escalante, 160, 46011 València | WhatsApp disponible: +34 685 41 27 63 | Sitio web existente: https://osbarquitectos.com | Instagram: @osbarquitectos | Facebook: osbarquitectos | Prospecto recopilado en relevamiento territorial Valencia 2026.",
    "createdAt": "2026-08-24T03:56:44.423Z",
    "updatedAt": "2026-09-23T03:56:44.414Z"
  },
  {
    "id": "vlc-2",
    "name": "Fandiño Arquitectura",
    "legalName": "Fandiño Arquitectura S.L.",
    "industry": "Arquitectura & Diseño",
    "contactName": "Arq. Carlos Fandiño",
    "contactRole": "Arquitecto Titular",
    "email": "contacto@fandinoarquitectura.es",
    "phone": "+34 963 71 89 20",
    "website": "https://fandinoarquitectura.es",
    "status": "lead",
    "estimatedValue": 2400,
    "assignedTo": "Stefi Del Papa",
    "techRequirements": "Modernización estética de sitio web, portfolio visual de proyectos en alta resolución y sistema automatizado de cotizaciones.",
    "notes": "Dirección: Carrer d'Escalante, 114, 46011 València | WhatsApp no registrado inicialmente | Sitio web existente: https://fandinoarquitectura.es | Facebook: fandinoarquitectura | Prospecto recopilado en relevamiento territorial Valencia 2026.",
    "createdAt": "2026-08-25T03:56:44.424Z",
    "updatedAt": "2026-09-23T03:56:44.414Z"
  },
  {
    "id": "vlc-3",
    "name": "Estudio Arquitectura Cabanyal (Vicente R.)",
    "legalName": "Estudio Arquitectura Cabanyal (Vicente R.) S.L.",
    "industry": "Arquitectura & Diseño",
    "contactName": "Vicente R.",
    "contactRole": "Arquitecto Titular",
    "email": "contacto@estudioarquitec.es",
    "phone": "+34 963 56 12 40",
    "status": "lead",
    "estimatedValue": 1950,
    "assignedTo": "Stefi Del Papa",
    "techRequirements": "Desarrollo de landing page/sitio web moderno optimizado para móviles, optimización SEO local en Valencia (Cabanyal/Marítim) y botón directo de atención WhatsApp.",
    "notes": "Dirección: Carrer del Progrés, 88, 46011 València | WhatsApp no registrado inicialmente | Sin sitio web actual (Oportunidad prioritaria de desarrollo) | Prospecto recopilado en relevamiento territorial Valencia 2026.",
    "createdAt": "2026-08-26T03:56:44.424Z",
    "updatedAt": "2026-09-23T03:56:44.414Z"
  },
  {
    "id": "vlc-4",
    "name": "Reforma y Arquitectura Marítim",
    "legalName": "Reforma y Arquitectura Marítim S.L.",
    "industry": "Arquitectura & Diseño",
    "contactName": "Dirección / Titular",
    "contactRole": "Arquitecto Titular",
    "email": "contacto@reformayarquite.es",
    "phone": "+34 644 19 82 05",
    "status": "lead",
    "estimatedValue": 1950,
    "assignedTo": "Lic. Mateo Rossi",
    "techRequirements": "Desarrollo de landing page/sitio web moderno optimizado para móviles, optimización SEO local en Valencia (Cabanyal/Marítim) y botón directo de atención WhatsApp.",
    "notes": "Dirección: Carrer d'Ernest Anastasio, 24, 46011 València | WhatsApp disponible: +34 644 19 82 05 | Sin sitio web actual (Oportunidad prioritaria de desarrollo) | Instagram: @reformasmaritim_vlc | Prospecto recopilado en relevamiento territorial Valencia 2026.",
    "createdAt": "2026-08-27T03:56:44.424Z",
    "updatedAt": "2026-09-23T03:56:44.414Z"
  },
  {
    "id": "vlc-5",
    "name": "Arquitectura Técnica & Peritajes Marítim",
    "legalName": "Arquitectura Técnica & Peritajes Marítim S.L.",
    "industry": "Arquitectura & Diseño",
    "contactName": "Dirección / Titular",
    "contactRole": "Arquitecto Titular",
    "email": "contacto@arquitecturatcn.es",
    "phone": "+34 963 55 41 12",
    "status": "lead",
    "estimatedValue": 1950,
    "assignedTo": "Stefi Del Papa",
    "techRequirements": "Desarrollo de landing page/sitio web moderno optimizado para móviles, optimización SEO local en Valencia (Cabanyal/Marítim) y botón directo de atención WhatsApp.",
    "notes": "Dirección: Carrer de la Barraca, 76, 46011 València | WhatsApp no registrado inicialmente | Sin sitio web actual (Oportunidad prioritaria de desarrollo) | Prospecto recopilado en relevamiento territorial Valencia 2026.",
    "createdAt": "2026-08-28T03:56:44.424Z",
    "updatedAt": "2026-09-23T03:56:44.414Z"
  },
  {
    "id": "vlc-6",
    "name": "Taller d'Arquitectura El Grau - Cabanyal",
    "legalName": "Taller d'Arquitectura El Grau - Cabanyal S.L.",
    "industry": "Arquitectura & Diseño",
    "contactName": "Dirección / Titular",
    "contactRole": "Arquitecto Titular",
    "email": "contacto@tallerdarquitec.es",
    "phone": "+34 963 67 30 19",
    "status": "lead",
    "estimatedValue": 1950,
    "assignedTo": "Stefi Del Papa",
    "techRequirements": "Desarrollo de landing page/sitio web moderno optimizado para móviles, optimización SEO local en Valencia (Cabanyal/Marítim) y botón directo de atención WhatsApp.",
    "notes": "Dirección: Carrer Josep Benlliure, 142, 46011 València | WhatsApp no registrado inicialmente | Sin sitio web actual (Oportunidad prioritaria de desarrollo) | Instagram: @tallerarquitecturamaritim | Facebook: tallerarquitecturamaritim | Prospecto recopilado en relevamiento territorial Valencia 2026.",
    "createdAt": "2026-08-29T03:56:44.424Z",
    "updatedAt": "2026-09-23T03:56:44.414Z"
  },
  {
    "id": "vlc-7",
    "name": "Clínica Dental Dr. Lluch",
    "legalName": "Clínica Dental Dr. Lluch S.L.",
    "industry": "Salud Dental & Odontología",
    "contactName": "Dr. Lluch",
    "contactRole": "Director Médico",
    "email": "contacto@clnicadentaldrl.es",
    "phone": "+34 963 71 52 33",
    "status": "lead",
    "estimatedValue": 1950,
    "assignedTo": "Lic. Mateo Rossi",
    "techRequirements": "Desarrollo de landing page/sitio web moderno optimizado para móviles, optimización SEO local en Valencia (Cabanyal/Marítim) y botón directo de atención WhatsApp.",
    "notes": "Dirección: Carrer del Doctor Lluch, 21, 46011 València | WhatsApp no registrado inicialmente | Sin sitio web actual (Oportunidad prioritaria de desarrollo) | Prospecto recopilado en relevamiento territorial Valencia 2026.",
    "createdAt": "2026-08-30T03:56:44.424Z",
    "updatedAt": "2026-09-23T03:56:44.414Z"
  },
  {
    "id": "vlc-8",
    "name": "Lainez Dental",
    "legalName": "Lainez Dental S.L.",
    "industry": "Salud Dental & Odontología",
    "contactName": "Dra. María Láinez",
    "contactRole": "Director Médico",
    "email": "contacto@lainezdental.com",
    "phone": "+34 963 22 75 14",
    "website": "https://lainezdental.com",
    "status": "lead",
    "estimatedValue": 3200,
    "assignedTo": "Stefi Del Papa",
    "techRequirements": "Portal de turnos online integrado con WhatsApp Business, ficha de paciente digital y recordatorios automáticos de consultas.",
    "notes": "Dirección: Carrer de la Serrería, 45, 46022 València (Eje Cabanyal) | WhatsApp disponible: +34 622 41 85 90 | Sitio web existente: https://lainezdental.com | Instagram: @lainezdental | Facebook: lainezdentalvalencia | Prospecto recopilado en relevamiento territorial Valencia 2026.",
    "createdAt": "2026-08-31T03:56:44.424Z",
    "updatedAt": "2026-09-23T03:56:44.414Z"
  },
  {
    "id": "vlc-9",
    "name": "Clínica Dental Dr. Vicente Faus",
    "legalName": "Clínica Dental Dr. Vicente Faus S.L.",
    "industry": "Salud Dental & Odontología",
    "contactName": "Dr. Vicente Faus",
    "contactRole": "Director Médico",
    "email": "contacto@drvicentefausdentista.com",
    "phone": "+34 960 45 40 20",
    "website": "https://drvicentefausdentista.com",
    "status": "lead",
    "estimatedValue": 3200,
    "assignedTo": "Stefi Del Papa",
    "techRequirements": "Portal de turnos online integrado con WhatsApp Business, ficha de paciente digital y recordatorios automáticos de consultas.",
    "notes": "Dirección: Carrer de Martí Grajales, 7, 46011 València | WhatsApp disponible: +34 695 32 18 44 | Sitio web existente: https://drvicentefausdentista.com | Instagram: @clinicadentalfaus | Facebook: clinicadentaldrvicentefaus | Prospecto recopilado en relevamiento territorial Valencia 2026.",
    "createdAt": "2026-09-01T03:56:44.424Z",
    "updatedAt": "2026-09-23T03:56:44.414Z"
  },
  {
    "id": "vlc-10",
    "name": "Clínica Dental Cabanyal",
    "legalName": "Clínica Dental Cabanyal S.L.",
    "industry": "Salud Dental & Odontología",
    "contactName": "Dirección / Titular",
    "contactRole": "Director Médico",
    "email": "contacto@clnicadentalcab.es",
    "phone": "+34 963 71 44 80",
    "status": "lead",
    "estimatedValue": 1950,
    "assignedTo": "Lic. Mateo Rossi",
    "techRequirements": "Desarrollo de landing page/sitio web moderno optimizado para móviles, optimización SEO local en Valencia (Cabanyal/Marítim) y botón directo de atención WhatsApp.",
    "notes": "Dirección: Carrer de la Reina, 112, 46011 València | WhatsApp no registrado inicialmente | Sin sitio web actual (Oportunidad prioritaria de desarrollo) | Facebook: dentalcabanyal | Prospecto recopilado en relevamiento territorial Valencia 2026.",
    "createdAt": "2026-09-02T03:56:44.424Z",
    "updatedAt": "2026-09-23T03:56:44.414Z"
  },
  {
    "id": "vlc-11",
    "name": "Clínica Dental Dra. Amparo Martí",
    "legalName": "Clínica Dental Dra. Amparo Martí S.L.",
    "industry": "Salud Dental & Odontología",
    "contactName": "Dra. Amparo Martí",
    "contactRole": "Director Médico",
    "email": "contacto@clnicadentaldra.es",
    "phone": "+34 963 72 19 02",
    "status": "lead",
    "estimatedValue": 1950,
    "assignedTo": "Stefi Del Papa",
    "techRequirements": "Desarrollo de landing page/sitio web moderno optimizado para móviles, optimización SEO local en Valencia (Cabanyal/Marítim) y botón directo de atención WhatsApp.",
    "notes": "Dirección: Carrer d'Escalante, 89, 46011 València | WhatsApp no registrado inicialmente | Sin sitio web actual (Oportunidad prioritaria de desarrollo) | Prospecto recopilado en relevamiento territorial Valencia 2026.",
    "createdAt": "2026-09-03T03:56:44.424Z",
    "updatedAt": "2026-09-23T03:56:44.414Z"
  },
  {
    "id": "vlc-12",
    "name": "Dental Marítimo (Dra. Sánchez)",
    "legalName": "Dental Marítimo (Dra. Sánchez) S.L.",
    "industry": "Salud Dental & Odontología",
    "contactName": "Dra. Carmen Sánchez",
    "contactRole": "Director Médico",
    "email": "contacto@dentalmartimodr.es",
    "phone": "+34 963 55 83 29",
    "status": "lead",
    "estimatedValue": 1950,
    "assignedTo": "Stefi Del Papa",
    "techRequirements": "Desarrollo de landing page/sitio web moderno optimizado para móviles, optimización SEO local en Valencia (Cabanyal/Marítim) y botón directo de atención WhatsApp.",
    "notes": "Dirección: Avinguda del Mediterrani, 18, 46011 València | WhatsApp no registrado inicialmente | Sin sitio web actual (Oportunidad prioritaria de desarrollo) | Prospecto recopilado en relevamiento territorial Valencia 2026.",
    "createdAt": "2026-09-04T03:56:44.424Z",
    "updatedAt": "2026-09-23T03:56:44.414Z"
  },
  {
    "id": "vlc-13",
    "name": "Centro AIRE (Fisioterapia y Podología)",
    "legalName": "Centro AIRE (Fisioterapia y Podología) S.L.",
    "industry": "Salud & Medicina",
    "contactName": "Dirección / Titular",
    "contactRole": "Director Médico",
    "email": "contacto@airevalencia.es",
    "phone": "+34 962 49 04 00",
    "website": "https://airevalencia.es",
    "status": "lead",
    "estimatedValue": 3200,
    "assignedTo": "Lic. Mateo Rossi",
    "techRequirements": "Portal de turnos online integrado con WhatsApp Business, ficha de paciente digital y recordatorios automáticos de consultas.",
    "notes": "Dirección: Carrer d'Enginyer Manuel Maese, 18, 46011 València | WhatsApp disponible: +34 640 07 95 96 | Sitio web existente: https://airevalencia.es | Instagram: @airevalencia | Facebook: airevalencia | Prospecto recopilado en relevamiento territorial Valencia 2026.",
    "createdAt": "2026-09-05T03:56:44.424Z",
    "updatedAt": "2026-09-23T03:56:44.414Z"
  },
  {
    "id": "vlc-14",
    "name": "Fisioterapia Marítimo Cabanyal",
    "legalName": "Fisioterapia Marítimo Cabanyal S.L.",
    "industry": "Fisioterapia & Podología",
    "contactName": "Dirección / Titular",
    "contactRole": "Director Médico",
    "email": "contacto@fisioterapiamar.es",
    "phone": "+34 963 56 70 88",
    "status": "lead",
    "estimatedValue": 1950,
    "assignedTo": "Stefi Del Papa",
    "techRequirements": "Desarrollo de landing page/sitio web moderno optimizado para móviles, optimización SEO local en Valencia (Cabanyal/Marítim) y botón directo de atención WhatsApp.",
    "notes": "Dirección: Carrer d'Ernest Anastasio, 15, 46011 València | WhatsApp disponible: +34 644 32 11 90 | Sin sitio web actual (Oportunidad prioritaria de desarrollo) | Instagram: @fisiomaritimocabanyal | Prospecto recopilado en relevamiento territorial Valencia 2026.",
    "createdAt": "2026-09-06T03:56:44.425Z",
    "updatedAt": "2026-09-23T03:56:44.414Z"
  },
  {
    "id": "vlc-15",
    "name": "Clínica Podológica Cabanyal",
    "legalName": "Clínica Podológica Cabanyal S.L.",
    "industry": "Fisioterapia & Podología",
    "contactName": "Dirección / Titular",
    "contactRole": "Director Médico",
    "email": "contacto@clnicapodolgica.es",
    "phone": "+34 963 71 63 94",
    "status": "lead",
    "estimatedValue": 1950,
    "assignedTo": "Stefi Del Papa",
    "techRequirements": "Desarrollo de landing page/sitio web moderno optimizado para móviles, optimización SEO local en Valencia (Cabanyal/Marítim) y botón directo de atención WhatsApp.",
    "notes": "Dirección: Carrer de la Barraca, 54, 46011 València | WhatsApp no registrado inicialmente | Sin sitio web actual (Oportunidad prioritaria de desarrollo) | Prospecto recopilado en relevamiento territorial Valencia 2026.",
    "createdAt": "2026-09-07T03:56:44.425Z",
    "updatedAt": "2026-09-23T03:56:44.414Z"
  },
  {
    "id": "vlc-16",
    "name": "Consultorio Médico y Psicológico Cabanyal",
    "legalName": "Consultorio Médico y Psicológico Cabanyal S.L.",
    "industry": "Salud & Medicina",
    "contactName": "Dirección / Titular",
    "contactRole": "Director Médico",
    "email": "contacto@consultoriomdic.es",
    "phone": "+34 963 55 90 12",
    "status": "lead",
    "estimatedValue": 1950,
    "assignedTo": "Lic. Mateo Rossi",
    "techRequirements": "Desarrollo de landing page/sitio web moderno optimizado para móviles, optimización SEO local en Valencia (Cabanyal/Marítim) y botón directo de atención WhatsApp.",
    "notes": "Dirección: Carrer de la Reina, 144, 46011 València | WhatsApp no registrado inicialmente | Sin sitio web actual (Oportunidad prioritaria de desarrollo) | Prospecto recopilado en relevamiento territorial Valencia 2026.",
    "createdAt": "2026-09-08T03:56:44.425Z",
    "updatedAt": "2026-09-23T03:56:44.414Z"
  },
  {
    "id": "vlc-17",
    "name": "Centro de Psicología y Logopedia Marítims",
    "legalName": "Centro de Psicología y Logopedia Marítims S.L.",
    "industry": "Salud & Medicina",
    "contactName": "Dirección / Titular",
    "contactRole": "Director Médico",
    "email": "contacto@psicologiamaritims.es",
    "phone": "+34 963 56 42 18",
    "website": "https://psicologiamaritims.es",
    "status": "lead",
    "estimatedValue": 3200,
    "assignedTo": "Stefi Del Papa",
    "techRequirements": "Portal de turnos online integrado con WhatsApp Business, ficha de paciente digital y recordatorios automáticos de consultas.",
    "notes": "Dirección: Carrer de Martí Grajales, 19, 46011 València | WhatsApp disponible: +34 633 81 22 50 | Sitio web existente: https://psicologiamaritims.es | Instagram: @psicologiamaritims | Facebook: psicologiamaritims | Prospecto recopilado en relevamiento territorial Valencia 2026.",
    "createdAt": "2026-09-09T03:56:44.425Z",
    "updatedAt": "2026-09-23T03:56:44.414Z"
  },
  {
    "id": "vlc-18",
    "name": "Fisioterapia & Osteopatía Escalante",
    "legalName": "Fisioterapia & Osteopatía Escalante S.L.",
    "industry": "Fisioterapia & Podología",
    "contactName": "Dirección / Titular",
    "contactRole": "Director Médico",
    "email": "contacto@fisioterapiaost.es",
    "phone": "+34 963 71 82 40",
    "status": "lead",
    "estimatedValue": 1950,
    "assignedTo": "Stefi Del Papa",
    "techRequirements": "Desarrollo de landing page/sitio web moderno optimizado para móviles, optimización SEO local en Valencia (Cabanyal/Marítim) y botón directo de atención WhatsApp.",
    "notes": "Dirección: Carrer d'Escalante, 65, 46011 València | WhatsApp disponible: +34 611 20 45 78 | Sin sitio web actual (Oportunidad prioritaria de desarrollo) | Instagram: @fisioosteocabanyal | Prospecto recopilado en relevamiento territorial Valencia 2026.",
    "createdAt": "2026-09-10T03:56:44.425Z",
    "updatedAt": "2026-09-23T03:56:44.414Z"
  },
  {
    "id": "vlc-19",
    "name": "Ángel Toledo Algarra Abogados",
    "legalName": "Ángel Toledo Algarra Abogados S.L.P.",
    "industry": "Servicios Jurídicos & Legal",
    "contactName": "Lic. Ángel Toledo Algarra",
    "contactRole": "Socio Director",
    "email": "contacto@angeltoledo.com",
    "phone": "+34 637 73 65 33",
    "website": "https://angeltoledo.com",
    "status": "lead",
    "estimatedValue": 2800,
    "assignedTo": "Lic. Mateo Rossi",
    "techRequirements": "Plataforma segura de consulta documental, portal de cliente para subida de facturas/expedientes y automatización de respuestas frecuentes.",
    "notes": "Dirección: Carrer de la Reina, 175, bjo, 46011 València | WhatsApp disponible: +34 637 73 65 33 | Sitio web existente: https://angeltoledo.com | Facebook: angeltoledoadvocat | Prospecto recopilado en relevamiento territorial Valencia 2026.",
    "createdAt": "2026-09-11T03:56:44.425Z",
    "updatedAt": "2026-09-23T03:56:44.414Z"
  },
  {
    "id": "vlc-20",
    "name": "Zabal Fernández Abogados",
    "legalName": "Zabal Fernández Abogados S.L.P.",
    "industry": "Servicios Jurídicos & Legal",
    "contactName": "Dirección / Titular",
    "contactRole": "Socio Director",
    "email": "contacto@zabalfernndezab.es",
    "phone": "+34 963 71 08 55",
    "status": "lead",
    "estimatedValue": 1950,
    "assignedTo": "Stefi Del Papa",
    "techRequirements": "Desarrollo de landing page/sitio web moderno optimizado para móviles, optimización SEO local en Valencia (Cabanyal/Marítim) y botón directo de atención WhatsApp.",
    "notes": "Dirección: Carrer del Pintor Ferrandis, 31, 46011 València | WhatsApp no registrado inicialmente | Sin sitio web actual (Oportunidad prioritaria de desarrollo) | Prospecto recopilado en relevamiento territorial Valencia 2026.",
    "createdAt": "2026-09-12T03:56:44.425Z",
    "updatedAt": "2026-09-23T03:56:44.414Z"
  },
  {
    "id": "vlc-21",
    "name": "Despacho Jurídico Marítim (G. Esteve)",
    "legalName": "Despacho Jurídico Marítim (G. Esteve) S.L.P.",
    "industry": "Servicios Jurídicos & Legal",
    "contactName": "Dr. G. Esteve",
    "contactRole": "Socio Director",
    "email": "contacto@despachojurdico.es",
    "phone": "+34 963 55 19 40",
    "status": "lead",
    "estimatedValue": 1950,
    "assignedTo": "Stefi Del Papa",
    "techRequirements": "Desarrollo de landing page/sitio web moderno optimizado para móviles, optimización SEO local en Valencia (Cabanyal/Marítim) y botón directo de atención WhatsApp.",
    "notes": "Dirección: Carrer Josep Benlliure, 98, 46011 València | WhatsApp no registrado inicialmente | Sin sitio web actual (Oportunidad prioritaria de desarrollo) | Prospecto recopilado en relevamiento territorial Valencia 2026.",
    "createdAt": "2026-09-13T03:56:44.425Z",
    "updatedAt": "2026-09-23T03:56:44.414Z"
  },
  {
    "id": "vlc-22",
    "name": "Bufete Cabanyal Legal",
    "legalName": "Bufete Cabanyal Legal S.L.P.",
    "industry": "Servicios Jurídicos & Legal",
    "contactName": "Dirección / Titular",
    "contactRole": "Socio Director",
    "email": "contacto@bufetecabanyall.es",
    "phone": "+34 963 72 66 11",
    "status": "lead",
    "estimatedValue": 1950,
    "assignedTo": "Lic. Mateo Rossi",
    "techRequirements": "Desarrollo de landing page/sitio web moderno optimizado para móviles, optimización SEO local en Valencia (Cabanyal/Marítim) y botón directo de atención WhatsApp.",
    "notes": "Dirección: Carrer de la Barraca, 110, 46011 València | WhatsApp no registrado inicialmente | Sin sitio web actual (Oportunidad prioritaria de desarrollo) | Prospecto recopilado en relevamiento territorial Valencia 2026.",
    "createdAt": "2026-09-14T03:56:44.425Z",
    "updatedAt": "2026-09-23T03:56:44.414Z"
  },
  {
    "id": "vlc-23",
    "name": "Ortiz & Asociados Abogados",
    "legalName": "Ortiz & Asociados Abogados S.L.P.",
    "industry": "Servicios Jurídicos & Legal",
    "contactName": "Dirección / Titular",
    "contactRole": "Socio Director",
    "email": "contacto@ortizabogadoscabanyal.com",
    "phone": "+34 963 71 90 04",
    "website": "https://ortizabogadoscabanyal.com",
    "status": "lead",
    "estimatedValue": 2800,
    "assignedTo": "Stefi Del Papa",
    "techRequirements": "Plataforma segura de consulta documental, portal de cliente para subida de facturas/expedientes y automatización de respuestas frecuentes.",
    "notes": "Dirección: Carrer d'Escalante, 148, 46011 València | WhatsApp disponible: +34 644 90 12 30 | Sitio web existente: https://ortizabogadoscabanyal.com | Instagram: @ortizabogadosvlc | Facebook: ortizabogadosvalencia | Prospecto recopilado en relevamiento territorial Valencia 2026.",
    "createdAt": "2026-09-15T03:56:44.425Z",
    "updatedAt": "2026-09-23T03:56:44.414Z"
  },
  {
    "id": "vlc-24",
    "name": "Gestoría Cabanyal SLP",
    "legalName": "Gestoría Cabanyal SLP S.L.",
    "industry": "Asesoría Contable & Fiscal",
    "contactName": "Dirección / Titular",
    "contactRole": "Socio Gestor",
    "email": "contacto@gestoracabanyal.es",
    "phone": "+34 963 71 14 50",
    "status": "lead",
    "estimatedValue": 1950,
    "assignedTo": "Stefi Del Papa",
    "techRequirements": "Desarrollo de landing page/sitio web moderno optimizado para móviles, optimización SEO local en Valencia (Cabanyal/Marítim) y botón directo de atención WhatsApp.",
    "notes": "Dirección: Carrer de la Reina, 80, bjo, 46011 València | WhatsApp no registrado inicialmente | Sin sitio web actual (Oportunidad prioritaria de desarrollo) | Facebook: gestoriacabanyalslp | Prospecto recopilado en relevamiento territorial Valencia 2026.",
    "createdAt": "2026-09-16T03:56:44.425Z",
    "updatedAt": "2026-09-23T03:56:44.414Z"
  },
  {
    "id": "vlc-25",
    "name": "Canyamelar Assessors",
    "legalName": "Canyamelar Assessors S.L.",
    "industry": "Asesoría Contable & Fiscal",
    "contactName": "Dirección / Titular",
    "contactRole": "Socio Gestor",
    "email": "contacto@canyamelarassessors.es",
    "phone": "+34 963 71 85 10",
    "website": "https://canyamelarassessors.es",
    "status": "lead",
    "estimatedValue": 2800,
    "assignedTo": "Lic. Mateo Rossi",
    "techRequirements": "Plataforma segura de consulta documental, portal de cliente para subida de facturas/expedientes y automatización de respuestas frecuentes.",
    "notes": "Dirección: Carrer de la Barraca, 127, 1º-4ª, 46011 València | WhatsApp disponible: +34 670 41 22 89 | Sitio web existente: https://canyamelarassessors.es | Instagram: @canyamelarassessors | Facebook: canyamelarassessors | Prospecto recopilado en relevamiento territorial Valencia 2026.",
    "createdAt": "2026-09-17T03:56:44.425Z",
    "updatedAt": "2026-09-23T03:56:44.414Z"
  },
  {
    "id": "vlc-26",
    "name": "Gestoría Crespo",
    "legalName": "Gestoría Crespo S.L.P.",
    "industry": "Asesoría Contable & Fiscal",
    "contactName": "Dirección / Titular",
    "contactRole": "Socio Gestor",
    "email": "contacto@gestoracrespo.es",
    "phone": "+34 963 71 33 08",
    "status": "lead",
    "estimatedValue": 1950,
    "assignedTo": "Stefi Del Papa",
    "techRequirements": "Desarrollo de landing page/sitio web moderno optimizado para móviles, optimización SEO local en Valencia (Cabanyal/Marítim) y botón directo de atención WhatsApp.",
    "notes": "Dirección: Carrer de la Reina, 210, 46011 València | WhatsApp no registrado inicialmente | Sin sitio web actual (Oportunidad prioritaria de desarrollo) | Prospecto recopilado en relevamiento territorial Valencia 2026.",
    "createdAt": "2026-09-18T03:56:44.425Z",
    "updatedAt": "2026-09-23T03:56:44.414Z"
  },
  {
    "id": "vlc-27",
    "name": "Asesorías Anelia",
    "legalName": "Asesorías Anelia S.L.",
    "industry": "Asesoría Contable & Fiscal",
    "contactName": "Dirección / Titular",
    "contactRole": "Socio Gestor",
    "email": "contacto@asesorasanelia.es",
    "phone": "+34 963 56 31 75",
    "status": "lead",
    "estimatedValue": 1950,
    "assignedTo": "Stefi Del Papa",
    "techRequirements": "Desarrollo de landing page/sitio web moderno optimizado para móviles, optimización SEO local en Valencia (Cabanyal/Marítim) y botón directo de atención WhatsApp.",
    "notes": "Dirección: Carrer de Pedro Maza, 14, 46011 València | WhatsApp no registrado inicialmente | Sin sitio web actual (Oportunidad prioritaria de desarrollo) | Prospecto recopilado en relevamiento territorial Valencia 2026.",
    "createdAt": "2026-09-19T03:56:44.425Z",
    "updatedAt": "2026-09-23T03:56:44.414Z"
  },
  {
    "id": "vlc-28",
    "name": "Asesoría Fiscal & Laboral Marítimo",
    "legalName": "Asesoría Fiscal & Laboral Marítimo S.L.",
    "industry": "Asesoría Contable & Fiscal",
    "contactName": "Dirección / Titular",
    "contactRole": "Socio Gestor",
    "email": "contacto@asesorafiscalla.es",
    "phone": "+34 963 72 05 91",
    "status": "lead",
    "estimatedValue": 1950,
    "assignedTo": "Lic. Mateo Rossi",
    "techRequirements": "Desarrollo de landing page/sitio web moderno optimizado para móviles, optimización SEO local en Valencia (Cabanyal/Marítim) y botón directo de atención WhatsApp.",
    "notes": "Dirección: Carrer de la Reina, 45, 46011 València | WhatsApp no registrado inicialmente | Sin sitio web actual (Oportunidad prioritaria de desarrollo) | Prospecto recopilado en relevamiento territorial Valencia 2026.",
    "createdAt": "2026-09-20T03:56:44.425Z",
    "updatedAt": "2026-09-23T03:56:44.414Z"
  },
  {
    "id": "vlc-29",
    "name": "Gestoría Administrativa Benlliure",
    "legalName": "Gestoría Administrativa Benlliure S.L.P.",
    "industry": "Asesoría Contable & Fiscal",
    "contactName": "Dirección / Titular",
    "contactRole": "Socio Gestor",
    "email": "contacto@gestoraadminist.es",
    "phone": "+34 963 71 95 62",
    "status": "lead",
    "estimatedValue": 1950,
    "assignedTo": "Stefi Del Papa",
    "techRequirements": "Desarrollo de landing page/sitio web moderno optimizado para móviles, optimización SEO local en Valencia (Cabanyal/Marítim) y botón directo de atención WhatsApp.",
    "notes": "Dirección: Carrer Josep Benlliure, 62, 46011 València | WhatsApp no registrado inicialmente | Sin sitio web actual (Oportunidad prioritaria de desarrollo) | Prospecto recopilado en relevamiento territorial Valencia 2026.",
    "createdAt": "2026-09-21T03:56:44.425Z",
    "updatedAt": "2026-09-23T03:56:44.414Z"
  },
  {
    "id": "vlc-30",
    "name": "M. Soler Assessors & Consultors",
    "legalName": "M. Soler Assessors & Consultors S.L.",
    "industry": "Asesoría Contable & Fiscal",
    "contactName": "M. Soler",
    "contactRole": "Titular / Decisor Principal",
    "email": "contacto@msolerassessors.com",
    "phone": "+34 963 55 64 30",
    "website": "https://msolerassessors.com",
    "status": "lead",
    "estimatedValue": 2800,
    "assignedTo": "Stefi Del Papa",
    "techRequirements": "Plataforma segura de consulta documental, portal de cliente para subida de facturas/expedientes y automatización de respuestas frecuentes.",
    "notes": "Dirección: Carrer del Progrés, 102, 46011 València | WhatsApp disponible: +34 650 92 11 47 | Sitio web existente: https://msolerassessors.com | Facebook: msolerassessors | Prospecto recopilado en relevamiento territorial Valencia 2026.",
    "createdAt": "2026-09-22T03:56:44.425Z",
    "updatedAt": "2026-09-23T03:56:44.414Z"
  },
  {
    "id": "vlc-31",
    "name": "Cabanyal Consulting Fiscal & Legal",
    "legalName": "Cabanyal Consulting Fiscal & Legal S.L.",
    "industry": "Servicios Jurídicos & Legal",
    "contactName": "Dirección / Titular",
    "contactRole": "Socio Director",
    "email": "contacto@cabanyalconsult.es",
    "phone": "+34 963 71 28 00",
    "status": "lead",
    "estimatedValue": 1950,
    "assignedTo": "Lic. Mateo Rossi",
    "techRequirements": "Desarrollo de landing page/sitio web moderno optimizado para móviles, optimización SEO local en Valencia (Cabanyal/Marítim) y botón directo de atención WhatsApp.",
    "notes": "Dirección: Carrer d'Ample, 19, 46011 València | WhatsApp no registrado inicialmente | Sin sitio web actual (Oportunidad prioritaria de desarrollo) | Prospecto recopilado en relevamiento territorial Valencia 2026.",
    "createdAt": "2026-09-23T03:56:44.425Z",
    "updatedAt": "2026-09-23T03:56:44.414Z"
  }
];

export const initialValenciaIssues = [
  {
    "id": "iss-vlc-1",
    "issueKey": "IAT-201",
    "title": "Auditoría inicial de presencia digital y ficha Google Maps para clínicas dentales de Valencia",
    "description": "Relevar fichas de Google Business y optimización local para Lainez Dental, Dr. Lluch y Dr. Vicente Faus.",
    "type": "consulting",
    "status": "backlog",
    "priority": "high",
    "companyId": "vlc-8",
    "assignedTo": "Stefi Del Papa",
    "storyPoints": 5,
    "value": 2400,
    "dueDate": "2026-09-30T03:56:44.425Z",
    "tags": "[\"Valencia\",\"Salud Dental\",\"SEO Local\"]",
    "createdAt": "2026-09-20T03:56:44.425Z",
    "updatedAt": "2026-09-23T03:56:44.414Z"
  },
  {
    "id": "iss-vlc-2",
    "issueKey": "IAT-202",
    "title": "Diseño de propuesta para agendamiento de turnos online y WhatsApp en Centro AIRE",
    "description": "Estructurar flujo conversacional para reservas de sesiones de fisioterapia y podología con sincronización a calendario.",
    "type": "automation",
    "status": "todo",
    "priority": "highest",
    "companyId": "vlc-13",
    "assignedTo": "Stefi Del Papa",
    "storyPoints": 5,
    "value": 3200,
    "dueDate": "2026-09-28T03:56:44.425Z",
    "tags": "[\"Fisioterapia\",\"WhatsApp Bot\",\"Citas\"]",
    "createdAt": "2026-09-21T03:56:44.425Z",
    "updatedAt": "2026-09-23T03:56:44.414Z"
  },
  {
    "id": "iss-vlc-3",
    "issueKey": "IAT-203",
    "title": "Propuesta de arquitectura web y catálogo visual para OSB Arquitectos y Fandiño Arquitectura",
    "description": "Armar mockup de portfolio minimalista con carga ultrarrápida de imágenes WebP y formulario de cotización de proyectos.",
    "type": "task",
    "status": "todo",
    "priority": "high",
    "companyId": "vlc-1",
    "assignedTo": "Lic. Mateo Rossi",
    "storyPoints": 8,
    "value": 2800,
    "dueDate": "2026-09-29T03:56:44.425Z",
    "tags": "[\"Arquitectura\",\"Web Design\",\"Portfolio\"]",
    "createdAt": "2026-09-21T03:56:44.425Z",
    "updatedAt": "2026-09-23T03:56:44.414Z"
  },
  {
    "id": "iss-vlc-4",
    "issueKey": "IAT-204",
    "title": "Preparación de dossier de digitalización y portal de cliente para Gestoría Cabanyal y Canyamelar Assessors",
    "description": "Relevar requerimientos para recepción automatizada de facturas y consultas fiscales de autónomos en el Marítim.",
    "type": "consulting",
    "status": "backlog",
    "priority": "medium",
    "companyId": "vlc-24",
    "assignedTo": "Stefi Del Papa",
    "storyPoints": 5,
    "value": 2600,
    "dueDate": "2026-10-03T03:56:44.425Z",
    "tags": "[\"Gestoría\",\"Portal Cliente\",\"Fiscal\"]",
    "createdAt": "2026-09-22T03:56:44.425Z",
    "updatedAt": "2026-09-23T03:56:44.414Z"
  },
  {
    "id": "iss-vlc-5",
    "issueKey": "IAT-205",
    "title": "Estandarización de propuesta de servicios legales digitales para Ángel Toledo Algarra Abogados",
    "description": "Preparar análisis de canal de captación de casos y agendamiento previo de consultas jurídicas presenciales.",
    "type": "lead",
    "status": "backlog",
    "priority": "medium",
    "companyId": "vlc-19",
    "assignedTo": "Stefi Del Papa",
    "storyPoints": 3,
    "value": 2200,
    "dueDate": "2026-10-01T03:56:44.425Z",
    "tags": "[\"Legal\",\"Abogacía\",\"Valencia\"]",
    "createdAt": "2026-09-22T03:56:44.425Z",
    "updatedAt": "2026-09-23T03:56:44.414Z"
  },
  {
    "id": "iss-vlc-6",
    "issueKey": "IAT-206",
    "title": "Campaña de primer contacto para negocios sin sitio web en Carrer de la Reina y Escalante",
    "description": "Contacto inicial de relevamiento con comercios y despachos que actualmente sólo tienen ficha básica o carecen de web.",
    "type": "lead",
    "status": "todo",
    "priority": "high",
    "companyId": "vlc-3",
    "assignedTo": "Stefi Del Papa",
    "storyPoints": 5,
    "value": 3900,
    "dueDate": "2026-09-27T03:56:44.425Z",
    "tags": "[\"Prospección\",\"Primer Contacto\",\"Península\"]",
    "createdAt": "2026-09-23T03:56:44.414Z",
    "updatedAt": "2026-09-23T03:56:44.414Z"
  },
  {
    "id": "iss-vlc-7",
    "issueKey": "IAT-207",
    "title": "Configuración de embudo comercial y trazabilidad de contactos para Stefi Del Papa y Admin",
    "description": "Definir métricas de tasa de respuesta telefónica y conversión a reuniones presenciales / videollamadas en Valencia.",
    "type": "task",
    "status": "todo",
    "priority": "highest",
    "companyId": null,
    "assignedTo": "Lic. Mateo Rossi",
    "storyPoints": 3,
    "value": 0,
    "dueDate": "2026-09-26T03:56:44.425Z",
    "tags": "[\"CRM Setup\",\"Admin\",\"Estrategia\"]",
    "createdAt": "2026-09-23T03:56:44.414Z",
    "updatedAt": "2026-09-23T03:56:44.414Z"
  }
];

export const initialValenciaActivities = [
  {
    "id": "act-vlc-1",
    "companyId": "vlc-1",
    "type": "note",
    "summary": "Relevamiento territorial de estudio de arquitectura",
    "details": "Estudio de arquitectura consolidado en Carrer Escalante con sitio web activo. Oportunidad en optimización de portfolio y automatización de recepción de briefs.",
    "author": "Stefi Del Papa",
    "nextAction": "Preparar diagnóstico web personalizado",
    "nextActionDate": "2026-09-26T03:56:44.425Z",
    "createdAt": "2026-09-21T03:56:44.425Z"
  },
  {
    "id": "act-vlc-2",
    "companyId": "vlc-8",
    "type": "note",
    "summary": "Identificación de requerimientos de agendamiento online",
    "details": "Clínica dental con alta concurrencia en Serrería. Cuentan con WhatsApp pero sin turnero automático integrado a su sitio web.",
    "author": "Stefi Del Papa",
    "nextAction": "Contacto con Dra. Láinez para presentación breve",
    "nextActionDate": "2026-09-27T03:56:44.425Z",
    "createdAt": "2026-09-22T03:56:44.425Z"
  },
  {
    "id": "act-vlc-3",
    "companyId": "vlc-13",
    "type": "note",
    "summary": "Ficha de contacto y servicios en Centro AIRE",
    "details": "Centro multidisciplinar de fisioterapia y podología. Tienen web propia y actividad en redes. Excelente prospecto para canal de reservas 24/7.",
    "author": "Lic. Mateo Rossi",
    "nextAction": "Revisión conjunta con Stefi de propuesta de bot WhatsApp",
    "nextActionDate": "2026-09-25T03:56:44.425Z",
    "createdAt": "2026-09-23T03:56:44.414Z"
  }
];
