// Seed dataset for iAtomica CRM & Jira Suite - Valencia 2026
// Sourced from commercial prospecting dataset in Valencia (Cabanyal, Marítim, Serrería)
// Linked to Stefi Del Papa (Project Lead · España) and Lic. Mateo Rossi (Admin)

export const initialValenciaCompanies = [
  {
    "id": "vlc-1",
    "name": "OSB Arquitectos",
    "legalName": "OSB Arquitectos S.L.",
    "industry": "Arquitectura & Diseño",
    "contactName": "Dirección de Estudio OSB",
    "contactRole": "Arquitecto Titular",
    "email": "contacto@osbarquitectos.com",
    "phone": "+34 963 20 40 85",
    "website": "https://osbarquitectos.com",
    "status": "lead",
    "estimatedValue": 0,
    "territory": "espana",
    "assignedTo": "Lic. Mateo Rossi",
    "techRequirements": "Modernización estética de sitio web, portfolio visual de proyectos en alta resolución y sistema automatizado de cotizaciones.",
    "notes": "Dirección: Carrer d'Escalante, 160, 46011 València | WhatsApp disponible: +34 685 41 27 63 | Sitio web existente: https://osbarquitectos.com | Instagram: @osbarquitectos | Facebook: osbarquitectos | Prospecto recopilado en relevamiento territorial Valencia 2026.",
    "createdAt": "2026-08-24T03:56:44.423Z",
    "updatedAt": "2026-09-23T03:56:44.414Z"
  },
  {
    "id": "vlc-2",
    "name": "Fandiño Arquitectura",
    "legalName": "Fandiño Arquitectura S.L.",
    "industry": "Arquitectura & Diseño",
    "contactName": "Arq. Carlos Fandiño",
    "contactRole": "Arquitecto Titular",
    "email": "contacto@fandinoarquitectura.es",
    "phone": "+34 963 71 89 20",
    "website": "https://fandinoarquitectura.es",
    "status": "lead",
    "estimatedValue": 0,
    "territory": "espana",
    "assignedTo": "Stefi Del Papa",
    "techRequirements": "Modernización estética de sitio web, portfolio visual de proyectos en alta resolución y sistema automatizado de cotizaciones.",
    "notes": "Dirección: Carrer d'Escalante, 114, 46011 València | WhatsApp no registrado inicialmente | Sitio web existente: https://fandinoarquitectura.es | Facebook: fandinoarquitectura | Prospecto recopilado en relevamiento territorial Valencia 2026.",
    "createdAt": "2026-08-25T03:56:44.424Z",
    "updatedAt": "2026-09-23T03:56:44.414Z"
  },
  {
    "id": "vlc-3",
    "name": "Estudio Arquitectura Cabanyal (Vicente R.)",
    "legalName": "Estudio Arquitectura Cabanyal (Vicente R.) S.L.",
    "industry": "Arquitectura & Diseño",
    "contactName": "Vicente R.",
    "contactRole": "Arquitecto Titular",
    "email": "contacto@estudioarquitec.es",
    "phone": "+34 963 56 12 40",
    "status": "lead",
    "estimatedValue": 0,
    "territory": "espana",
    "assignedTo": "Stefi Del Papa",
    "techRequirements": "Desarrollo de landing page/sitio web moderno optimizado para móviles, optimización SEO local en Valencia (Cabanyal/Marítim) y botón directo de atención WhatsApp.",
    "notes": "Dirección: Carrer del Progrés, 88, 46011 València | WhatsApp no registrado inicialmente | Sin sitio web actual (Oportunidad prioritaria de desarrollo) | Prospecto recopilado en relevamiento territorial Valencia 2026.",
    "createdAt": "2026-08-26T03:56:44.424Z",
    "updatedAt": "2026-09-23T03:56:44.414Z"
  },
  {
    "id": "vlc-4",
    "name": "Reforma y Arquitectura Marítim",
    "legalName": "Reforma y Arquitectura Marítim S.L.",
    "industry": "Arquitectura & Diseño",
    "contactName": "Dirección / Titular",
    "contactRole": "Arquitecto Titular",
    "email": "contacto@reformayarquite.es",
    "phone": "+34 644 19 82 05",
    "status": "lead",
    "estimatedValue": 0,
    "territory": "espana",
    "assignedTo": "Lic. Mateo Rossi",
    "techRequirements": "Desarrollo de landing page/sitio web moderno optimizado para móviles, optimización SEO local en Valencia (Cabanyal/Marítim) y botón directo de atención WhatsApp.",
    "notes": "Dirección: Carrer d'Ernest Anastasio, 24, 46011 València | WhatsApp disponible: +34 644 19 82 05 | Sin sitio web actual (Oportunidad prioritaria de desarrollo) | Instagram: @reformasmaritim_vlc | Prospecto recopilado en relevamiento territorial Valencia 2026.",
    "createdAt": "2026-08-27T03:56:44.424Z",
    "updatedAt": "2026-09-23T03:56:44.414Z"
  },
  {
    "id": "vlc-5",
    "name": "Arquitectura Técnica & Peritajes Marítim",
    "legalName": "Arquitectura Técnica & Peritajes Marítim S.L.",
    "industry": "Arquitectura & Diseño",
    "contactName": "Dirección / Titular",
    "contactRole": "Arquitecto Titular",
    "email": "contacto@arquitecturatcn.es",
    "phone": "+34 963 55 41 12",
    "status": "lead",
    "estimatedValue": 0,
    "territory": "espana",
    "assignedTo": "Stefi Del Papa",
    "techRequirements": "Desarrollo de landing page/sitio web moderno optimizado para móviles, optimización SEO local en Valencia (Cabanyal/Marítim) y botón directo de atención WhatsApp.",
    "notes": "Dirección: Carrer de la Barraca, 76, 46011 València | WhatsApp no registrado inicialmente | Sin sitio web actual (Oportunidad prioritaria de desarrollo) | Prospecto recopilado en relevamiento territorial Valencia 2026.",
    "createdAt": "2026-08-28T03:56:44.424Z",
    "updatedAt": "2026-09-23T03:56:44.414Z"
  },
  {
    "id": "vlc-6",
    "name": "Taller d'Arquitectura El Grau - Cabanyal",
    "legalName": "Taller d'Arquitectura El Grau - Cabanyal S.L.",
    "industry": "Arquitectura & Diseño",
    "contactName": "Dirección / Titular",
    "contactRole": "Arquitecto Titular",
    "email": "contacto@tallerdarquitec.es",
    "phone": "+34 963 67 30 19",
    "status": "lead",
    "estimatedValue": 0,
    "territory": "espana",
    "assignedTo": "Stefi Del Papa",
    "techRequirements": "Desarrollo de landing page/sitio web moderno optimizado para móviles, optimización SEO local en Valencia (Cabanyal/Marítim) y botón directo de atención WhatsApp.",
    "notes": "Dirección: Carrer Josep Benlliure, 142, 46011 València | WhatsApp no registrado inicialmente | Sin sitio web actual (Oportunidad prioritaria de desarrollo) | Instagram: @tallerarquitecturamaritim | Facebook: tallerarquitecturamaritim | Prospecto recopilado en relevamiento territorial Valencia 2026.",
    "createdAt": "2026-08-29T03:56:44.424Z",
    "updatedAt": "2026-09-23T03:56:44.414Z"
  },
  {
    "id": "vlc-7",
    "name": "Clínica Dental Dr. Lluch",
    "legalName": "Clínica Dental Dr. Lluch S.L.",
    "industry": "Salud Dental & Odontología",
    "contactName": "Dr. Lluch",
    "contactRole": "Director Médico",
    "email": "contacto@clnicadentaldrl.es",
    "phone": "+34 963 71 52 33",
    "status": "lead",
    "estimatedValue": 0,
    "territory": "espana",
    "assignedTo": "Lic. Mateo Rossi",
    "techRequirements": "Desarrollo de landing page/sitio web moderno optimizado para móviles, optimización SEO local en Valencia (Cabanyal/Marítim) y botón directo de atención WhatsApp.",
    "notes": "Dirección: Carrer del Doctor Lluch, 21, 46011 València | WhatsApp no registrado inicialmente | Sin sitio web actual (Oportunidad prioritaria de desarrollo) | Prospecto recopilado en relevamiento territorial Valencia 2026.",
    "createdAt": "2026-08-30T03:56:44.424Z",
    "updatedAt": "2026-09-23T03:56:44.414Z"
  },
  {
    "id": "vlc-8",
    "name": "Lainez Dental",
    "legalName": "Lainez Dental S.L.",
    "industry": "Salud Dental & Odontología",
    "contactName": "Dra. María Láinez",
    "contactRole": "Director Médico",
    "email": "contacto@lainezdental.com",
    "phone": "+34 963 22 75 14",
    "website": "https://lainezdental.com",
    "status": "lead",
    "estimatedValue": 0,
    "territory": "espana",
    "assignedTo": "Stefi Del Papa",
    "techRequirements": "Portal de turnos online integrado con WhatsApp Business, ficha de paciente digital y recordatorios automáticos de consultas.",
    "notes": "Dirección: Carrer de la Serrería, 45, 46022 València (Eje Cabanyal) | WhatsApp disponible: +34 622 41 85 90 | Sitio web existente: https://lainezdental.com | Instagram: @lainezdental | Facebook: lainezdentalvalencia | Prospecto recopilado en relevamiento territorial Valencia 2026.",
    "createdAt": "2026-08-31T03:56:44.424Z",
    "updatedAt": "2026-09-23T03:56:44.414Z"
  },
  {
    "id": "vlc-9",
    "name": "Clínica Dental Dr. Vicente Faus",
    "legalName": "Clínica Dental Dr. Vicente Faus S.L.",
    "industry": "Salud Dental & Odontología",
    "contactName": "Dr. Vicente Faus",
    "contactRole": "Director Médico",
    "email": "contacto@drvicentefausdentista.com",
    "phone": "+34 960 45 40 20",
    "website": "https://drvicentefausdentista.com",
    "status": "lead",
    "estimatedValue": 0,
    "territory": "espana",
    "assignedTo": "Stefi Del Papa",
    "techRequirements": "Portal de turnos online integrado con WhatsApp Business, ficha de paciente digital y recordatorios automáticos de consultas.",
    "notes": "Dirección: Carrer de Martí Grajales, 7, 46011 València | WhatsApp disponible: +34 695 32 18 44 | Sitio web existente: https://drvicentefausdentista.com | Instagram: @clinicadentalfaus | Facebook: clinicadentaldrvicentefaus | Prospecto recopilado en relevamiento territorial Valencia 2026.",
    "createdAt": "2026-09-01T03:56:44.424Z",
    "updatedAt": "2026-09-23T03:56:44.414Z"
  },
  {
    "id": "vlc-10",
    "name": "Clínica Dental Cabanyal",
    "legalName": "Clínica Dental Cabanyal S.L.",
    "industry": "Salud Dental & Odontología",
    "contactName": "Dirección / Titular",
    "contactRole": "Director Médico",
    "email": "contacto@clnicadentalcab.es",
    "phone": "+34 963 71 44 80",
    "status": "lead",
    "estimatedValue": 0,
    "territory": "espana",
    "assignedTo": "Lic. Mateo Rossi",
    "techRequirements": "Desarrollo de landing page/sitio web moderno optimizado para móviles, optimización SEO local en Valencia (Cabanyal/Marítim) y botón directo de atención WhatsApp.",
    "notes": "Dirección: Carrer de la Reina, 112, 46011 València | WhatsApp no registrado inicialmente | Sin sitio web actual (Oportunidad prioritaria de desarrollo) | Facebook: dentalcabanyal | Prospecto recopilado en relevamiento territorial Valencia 2026.",
    "createdAt": "2026-09-02T03:56:44.424Z",
    "updatedAt": "2026-09-23T03:56:44.414Z"
  },
  {
    "id": "vlc-11",
    "name": "Clínica Dental Dra. Amparo Martí",
    "legalName": "Clínica Dental Dra. Amparo Martí S.L.",
    "industry": "Salud Dental & Odontología",
    "contactName": "Dra. Amparo Martí",
    "contactRole": "Director Médico",
    "email": "contacto@clnicadentaldra.es",
    "phone": "+34 963 72 19 02",
    "status": "lead",
    "estimatedValue": 0,
    "territory": "espana",
    "assignedTo": "Stefi Del Papa",
    "techRequirements": "Desarrollo de landing page/sitio web moderno optimizado para móviles, optimización SEO local en Valencia (Cabanyal/Marítim) y botón directo de atención WhatsApp.",
    "notes": "Dirección: Carrer d'Escalante, 89, 46011 València | WhatsApp no registrado inicialmente | Sin sitio web actual (Oportunidad prioritaria de desarrollo) | Prospecto recopilado en relevamiento territorial Valencia 2026.",
    "createdAt": "2026-09-03T03:56:44.424Z",
    "updatedAt": "2026-09-23T03:56:44.414Z"
  },
  {
    "id": "vlc-12",
    "name": "Dental Marítimo (Dra. Sánchez)",
    "legalName": "Dental Marítimo (Dra. Sánchez) S.L.",
    "industry": "Salud Dental & Odontología",
    "contactName": "Dra. Carmen Sánchez",
    "contactRole": "Director Médico",
    "email": "contacto@dentalmartimodr.es",
    "phone": "+34 963 55 83 29",
    "status": "lead",
    "estimatedValue": 0,
    "territory": "espana",
    "assignedTo": "Stefi Del Papa",
    "techRequirements": "Desarrollo de landing page/sitio web moderno optimizado para móviles, optimización SEO local en Valencia (Cabanyal/Marítim) y botón directo de atención WhatsApp.",
    "notes": "Dirección: Avinguda del Mediterrani, 18, 46011 València | WhatsApp no registrado inicialmente | Sin sitio web actual (Oportunidad prioritaria de desarrollo) | Prospecto recopilado en relevamiento territorial Valencia 2026.",
    "createdAt": "2026-09-04T03:56:44.424Z",
    "updatedAt": "2026-09-23T03:56:44.414Z"
  },
  {
    "id": "vlc-13",
    "name": "Centro AIRE (Fisioterapia y Podología)",
    "legalName": "Centro AIRE (Fisioterapia y Podología) S.L.",
    "industry": "Salud & Medicina",
    "contactName": "Dirección / Titular",
    "contactRole": "Director Médico",
    "email": "contacto@airevalencia.es",
    "phone": "+34 962 49 04 00",
    "website": "https://airevalencia.es",
    "status": "lead",
    "estimatedValue": 0,
    "territory": "espana",
    "assignedTo": "Lic. Mateo Rossi",
    "techRequirements": "Portal de turnos online integrado con WhatsApp Business, ficha de paciente digital y recordatorios automáticos de consultas.",
    "notes": "Dirección: Carrer d'Enginyer Manuel Maese, 18, 46011 València | WhatsApp disponible: +34 640 07 95 96 | Sitio web existente: https://airevalencia.es | Instagram: @airevalencia | Facebook: airevalencia | Prospecto recopilado en relevamiento territorial Valencia 2026.",
    "createdAt": "2026-09-05T03:56:44.424Z",
    "updatedAt": "2026-09-23T03:56:44.414Z"
  },
  {
    "id": "vlc-14",
    "name": "Fisioterapia Marítimo Cabanyal",
    "legalName": "Fisioterapia Marítimo Cabanyal S.L.",
    "industry": "Fisioterapia & Podología",
    "contactName": "Dirección / Titular",
    "contactRole": "Director Médico",
    "email": "contacto@fisioterapiamar.es",
    "phone": "+34 963 56 70 88",
    "status": "lead",
    "estimatedValue": 0,
    "territory": "espana",
    "assignedTo": "Stefi Del Papa",
    "techRequirements": "Desarrollo de landing page/sitio web moderno optimizado para móviles, optimización SEO local en Valencia (Cabanyal/Marítim) y botón directo de atención WhatsApp.",
    "notes": "Dirección: Carrer d'Ernest Anastasio, 15, 46011 València | WhatsApp disponible: +34 644 32 11 90 | Sin sitio web actual (Oportunidad prioritaria de desarrollo) | Instagram: @fisiomaritimocabanyal | Prospecto recopilado en relevamiento territorial Valencia 2026.",
    "createdAt": "2026-09-06T03:56:44.425Z",
    "updatedAt": "2026-09-23T03:56:44.414Z"
  },
  {
    "id": "vlc-15",
    "name": "Clínica Podológica Cabanyal",
    "legalName": "Clínica Podológica Cabanyal S.L.",
    "industry": "Fisioterapia & Podología",
    "contactName": "Dirección / Titular",
    "contactRole": "Director Médico",
    "email": "contacto@clnicapodolgica.es",
    "phone": "+34 963 71 63 94",
    "status": "lead",
    "estimatedValue": 0,
    "territory": "espana",
    "assignedTo": "Stefi Del Papa",
    "techRequirements": "Desarrollo de landing page/sitio web moderno optimizado para móviles, optimización SEO local en Valencia (Cabanyal/Marítim) y botón directo de atención WhatsApp.",
    "notes": "Dirección: Carrer de la Barraca, 54, 46011 València | WhatsApp no registrado inicialmente | Sin sitio web actual (Oportunidad prioritaria de desarrollo) | Prospecto recopilado en relevamiento territorial Valencia 2026.",
    "createdAt": "2026-09-07T03:56:44.425Z",
    "updatedAt": "2026-09-23T03:56:44.414Z"
  },
  {
    "id": "vlc-16",
    "name": "Consultorio Médico y Psicológico Cabanyal",
    "legalName": "Consultorio Médico y Psicológico Cabanyal S.L.",
    "industry": "Salud & Medicina",
    "contactName": "Dirección / Titular",
    "contactRole": "Director Médico",
    "email": "contacto@consultoriomdic.es",
    "phone": "+34 963 55 90 12",
    "status": "lead",
    "estimatedValue": 0,
    "territory": "espana",
    "assignedTo": "Lic. Mateo Rossi",
    "techRequirements": "Desarrollo de landing page/sitio web moderno optimizado para móviles, optimización SEO local en Valencia (Cabanyal/Marítim) y botón directo de atención WhatsApp.",
    "notes": "Dirección: Carrer de la Reina, 144, 46011 València | WhatsApp no registrado inicialmente | Sin sitio web actual (Oportunidad prioritaria de desarrollo) | Prospecto recopilado en relevamiento territorial Valencia 2026.",
    "createdAt": "2026-09-08T03:56:44.425Z",
    "updatedAt": "2026-09-23T03:56:44.414Z"
  },
  {
    "id": "vlc-17",
    "name": "Centro de Psicología y Logopedia Marítims",
    "legalName": "Centro de Psicología y Logopedia Marítims S.L.",
    "industry": "Salud & Medicina",
    "contactName": "Dirección / Titular",
    "contactRole": "Director Médico",
    "email": "contacto@psicologiamaritims.es",
    "phone": "+34 963 56 42 18",
    "website": "https://psicologiamaritims.es",
    "status": "lead",
    "estimatedValue": 0,
    "territory": "espana",
    "assignedTo": "Stefi Del Papa",
    "techRequirements": "Portal de turnos online integrado con WhatsApp Business, ficha de paciente digital y recordatorios automáticos de consultas.",
    "notes": "Dirección: Carrer de Martí Grajales, 19, 46011 València | WhatsApp disponible: +34 633 81 22 50 | Sitio web existente: https://psicologiamaritims.es | Instagram: @psicologiamaritims | Facebook: psicologiamaritims | Prospecto recopilado en relevamiento territorial Valencia 2026.",
    "createdAt": "2026-09-09T03:56:44.425Z",
    "updatedAt": "2026-09-23T03:56:44.414Z"
  },
  {
    "id": "vlc-18",
    "name": "Fisioterapia & Osteopatía Escalante",
    "legalName": "Fisioterapia & Osteopatía Escalante S.L.",
    "industry": "Fisioterapia & Podología",
    "contactName": "Dirección / Titular",
    "contactRole": "Director Médico",
    "email": "contacto@fisioterapiaost.es",
    "phone": "+34 963 71 82 40",
    "status": "lead",
    "estimatedValue": 0,
    "territory": "espana",
    "assignedTo": "Stefi Del Papa",
    "techRequirements": "Desarrollo de landing page/sitio web moderno optimizado para móviles, optimización SEO local en Valencia (Cabanyal/Marítim) y botón directo de atención WhatsApp.",
    "notes": "Dirección: Carrer d'Escalante, 65, 46011 València | WhatsApp disponible: +34 611 20 45 78 | Sin sitio web actual (Oportunidad prioritaria de desarrollo) | Instagram: @fisioosteocabanyal | Prospecto recopilado en relevamiento territorial Valencia 2026.",
    "createdAt": "2026-09-10T03:56:44.425Z",
    "updatedAt": "2026-09-23T03:56:44.414Z"
  },
  {
    "id": "vlc-19",
    "name": "Ángel Toledo Algarra Abogados",
    "legalName": "Ángel Toledo Algarra Abogados S.L.P.",
    "industry": "Servicios Jurídicos & Legal",
    "contactName": "Lic. Ángel Toledo Algarra",
    "contactRole": "Socio Director",
    "email": "contacto@angeltoledo.com",
    "phone": "+34 637 73 65 33",
    "website": "https://angeltoledo.com",
    "status": "lead",
    "estimatedValue": 0,
    "territory": "espana",
    "assignedTo": "Lic. Mateo Rossi",
    "techRequirements": "Plataforma segura de consulta documental, portal de cliente para subida de facturas/expedientes y automatización de respuestas frecuentes.",
    "notes": "Dirección: Carrer de la Reina, 175, bjo, 46011 València | WhatsApp disponible: +34 637 73 65 33 | Sitio web existente: https://angeltoledo.com | Facebook: angeltoledoadvocat | Prospecto recopilado en relevamiento territorial Valencia 2026.",
    "createdAt": "2026-09-11T03:56:44.425Z",
    "updatedAt": "2026-09-23T03:56:44.414Z"
  },
  {
    "id": "vlc-20",
    "name": "Zabal Fernández Abogados",
    "legalName": "Zabal Fernández Abogados S.L.P.",
    "industry": "Servicios Jurídicos & Legal",
    "contactName": "Dirección / Titular",
    "contactRole": "Socio Director",
    "email": "contacto@zabalfernndezab.es",
    "phone": "+34 963 71 08 55",
    "status": "lead",
    "estimatedValue": 0,
    "territory": "espana",
    "assignedTo": "Stefi Del Papa",
    "techRequirements": "Desarrollo de landing page/sitio web moderno optimizado para móviles, optimización SEO local en Valencia (Cabanyal/Marítim) y botón directo de atención WhatsApp.",
    "notes": "Dirección: Carrer del Pintor Ferrandis, 31, 46011 València | WhatsApp no registrado inicialmente | Sin sitio web actual (Oportunidad prioritaria de desarrollo) | Prospecto recopilado en relevamiento territorial Valencia 2026.",
    "createdAt": "2026-09-12T03:56:44.425Z",
    "updatedAt": "2026-09-23T03:56:44.414Z"
  },
  {
    "id": "vlc-21",
    "name": "Despacho Jurídico Marítim (G. Esteve)",
    "legalName": "Despacho Jurídico Marítim (G. Esteve) S.L.P.",
    "industry": "Servicios Jurídicos & Legal",
    "contactName": "Dr. G. Esteve",
    "contactRole": "Socio Director",
    "email": "contacto@despachojurdico.es",
    "phone": "+34 963 55 19 40",
    "status": "lead",
    "estimatedValue": 0,
    "territory": "espana",
    "assignedTo": "Stefi Del Papa",
    "techRequirements": "Desarrollo de landing page/sitio web moderno optimizado para móviles, optimización SEO local en Valencia (Cabanyal/Marítim) y botón directo de atención WhatsApp.",
    "notes": "Dirección: Carrer Josep Benlliure, 98, 46011 València | WhatsApp no registrado inicialmente | Sin sitio web actual (Oportunidad prioritaria de desarrollo) | Prospecto recopilado en relevamiento territorial Valencia 2026.",
    "createdAt": "2026-09-13T03:56:44.425Z",
    "updatedAt": "2026-09-23T03:56:44.414Z"
  },
  {
    "id": "vlc-22",
    "name": "Bufete Cabanyal Legal",
    "legalName": "Bufete Cabanyal Legal S.L.P.",
    "industry": "Servicios Jurídicos & Legal",
    "contactName": "Dirección / Titular",
    "contactRole": "Socio Director",
    "email": "contacto@bufetecabanyall.es",
    "phone": "+34 963 72 66 11",
    "status": "lead",
    "estimatedValue": 0,
    "territory": "espana",
    "assignedTo": "Lic. Mateo Rossi",
    "techRequirements": "Desarrollo de landing page/sitio web moderno optimizado para móviles, optimización SEO local en Valencia (Cabanyal/Marítim) y botón directo de atención WhatsApp.",
    "notes": "Dirección: Carrer de la Barraca, 110, 46011 València | WhatsApp no registrado inicialmente | Sin sitio web actual (Oportunidad prioritaria de desarrollo) | Prospecto recopilado en relevamiento territorial Valencia 2026.",
    "createdAt": "2026-09-14T03:56:44.425Z",
    "updatedAt": "2026-09-23T03:56:44.414Z"
  },
  {
    "id": "vlc-23",
    "name": "Ortiz & Asociados Abogados",
    "legalName": "Ortiz & Asociados Abogados S.L.P.",
    "industry": "Servicios Jurídicos & Legal",
    "contactName": "Dirección / Titular",
    "contactRole": "Socio Director",
    "email": "contacto@ortizabogadoscabanyal.com",
    "phone": "+34 963 71 90 04",
    "website": "https://ortizabogadoscabanyal.com",
    "status": "lead",
    "estimatedValue": 0,
    "territory": "espana",
    "assignedTo": "Stefi Del Papa",
    "techRequirements": "Plataforma segura de consulta documental, portal de cliente para subida de facturas/expedientes y automatización de respuestas frecuentes.",
    "notes": "Dirección: Carrer d'Escalante, 148, 46011 València | WhatsApp disponible: +34 644 90 12 30 | Sitio web existente: https://ortizabogadoscabanyal.com | Instagram: @ortizabogadosvlc | Facebook: ortizabogadosvalencia | Prospecto recopilado en relevamiento territorial Valencia 2026.",
    "createdAt": "2026-09-15T03:56:44.425Z",
    "updatedAt": "2026-09-23T03:56:44.414Z"
  },
  {
    "id": "vlc-24",
    "name": "Gestoría Cabanyal SLP",
    "legalName": "Gestoría Cabanyal SLP S.L.",
    "industry": "Asesoría Contable & Fiscal",
    "contactName": "Dirección / Titular",
    "contactRole": "Socio Gestor",
    "email": "contacto@gestoracabanyal.es",
    "phone": "+34 963 71 14 50",
    "status": "lead",
    "estimatedValue": 0,
    "territory": "espana",
    "assignedTo": "Stefi Del Papa",
    "techRequirements": "Desarrollo de landing page/sitio web moderno optimizado para móviles, optimización SEO local en Valencia (Cabanyal/Marítim) y botón directo de atención WhatsApp.",
    "notes": "Dirección: Carrer de la Reina, 80, bjo, 46011 València | WhatsApp no registrado inicialmente | Sin sitio web actual (Oportunidad prioritaria de desarrollo) | Facebook: gestoriacabanyalslp | Prospecto recopilado en relevamiento territorial Valencia 2026.",
    "createdAt": "2026-09-16T03:56:44.425Z",
    "updatedAt": "2026-09-23T03:56:44.414Z"
  },
  {
    "id": "vlc-25",
    "name": "Canyamelar Assessors",
    "legalName": "Canyamelar Assessors S.L.",
    "industry": "Asesoría Contable & Fiscal",
    "contactName": "Dirección / Titular",
    "contactRole": "Socio Gestor",
    "email": "contacto@canyamelarassessors.es",
    "phone": "+34 963 71 85 10",
    "website": "https://canyamelarassessors.es",
    "status": "lead",
    "estimatedValue": 0,
    "territory": "espana",
    "assignedTo": "Lic. Mateo Rossi",
    "techRequirements": "Plataforma segura de consulta documental, portal de cliente para subida de facturas/expedientes y automatización de respuestas frecuentes.",
    "notes": "Dirección: Carrer de la Barraca, 127, 1º-4ª, 46011 València | WhatsApp disponible: +34 670 41 22 89 | Sitio web existente: https://canyamelarassessors.es | Instagram: @canyamelarassessors | Facebook: canyamelarassessors | Prospecto recopilado en relevamiento territorial Valencia 2026.",
    "createdAt": "2026-09-17T03:56:44.425Z",
    "updatedAt": "2026-09-23T03:56:44.414Z"
  },
  {
    "id": "vlc-26",
    "name": "Gestoría Crespo",
    "legalName": "Gestoría Crespo S.L.P.",
    "industry": "Asesoría Contable & Fiscal",
    "contactName": "Dirección / Titular",
    "contactRole": "Socio Gestor",
    "email": "contacto@gestoracrespo.es",
    "phone": "+34 963 71 33 08",
    "status": "lead",
    "estimatedValue": 0,
    "territory": "espana",
    "assignedTo": "Stefi Del Papa",
    "techRequirements": "Desarrollo de landing page/sitio web moderno optimizado para móviles, optimización SEO local en Valencia (Cabanyal/Marítim) y botón directo de atención WhatsApp.",
    "notes": "Dirección: Carrer de la Reina, 210, 46011 València | WhatsApp no registrado inicialmente | Sin sitio web actual (Oportunidad prioritaria de desarrollo) | Prospecto recopilado en relevamiento territorial Valencia 2026.",
    "createdAt": "2026-09-18T03:56:44.425Z",
    "updatedAt": "2026-09-23T03:56:44.414Z"
  },
  {
    "id": "vlc-27",
    "name": "Asesorías Anelia",
    "legalName": "Asesorías Anelia S.L.",
    "industry": "Asesoría Contable & Fiscal",
    "contactName": "Dirección / Titular",
    "contactRole": "Socio Gestor",
    "email": "contacto@asesorasanelia.es",
    "phone": "+34 963 56 31 75",
    "status": "lead",
    "estimatedValue": 0,
    "territory": "espana",
    "assignedTo": "Stefi Del Papa",
    "techRequirements": "Desarrollo de landing page/sitio web moderno optimizado para móviles, optimización SEO local en Valencia (Cabanyal/Marítim) y botón directo de atención WhatsApp.",
    "notes": "Dirección: Carrer de Pedro Maza, 14, 46011 València | WhatsApp no registrado inicialmente | Sin sitio web actual (Oportunidad prioritaria de desarrollo) | Prospecto recopilado en relevamiento territorial Valencia 2026.",
    "createdAt": "2026-09-19T03:56:44.425Z",
    "updatedAt": "2026-09-23T03:56:44.414Z"
  },
  {
    "id": "vlc-28",
    "name": "Asesoría Fiscal & Laboral Marítimo",
    "legalName": "Asesoría Fiscal & Laboral Marítimo S.L.",
    "industry": "Asesoría Contable & Fiscal",
    "contactName": "Dirección / Titular",
    "contactRole": "Socio Gestor",
    "email": "contacto@asesorafiscalla.es",
    "phone": "+34 963 72 05 91",
    "status": "lead",
    "estimatedValue": 0,
    "territory": "espana",
    "assignedTo": "Lic. Mateo Rossi",
    "techRequirements": "Desarrollo de landing page/sitio web moderno optimizado para móviles, optimización SEO local en Valencia (Cabanyal/Marítim) y botón directo de atención WhatsApp.",
    "notes": "Dirección: Carrer de la Reina, 45, 46011 València | WhatsApp no registrado inicialmente | Sin sitio web actual (Oportunidad prioritaria de desarrollo) | Prospecto recopilado en relevamiento territorial Valencia 2026.",
    "createdAt": "2026-09-20T03:56:44.425Z",
    "updatedAt": "2026-09-23T03:56:44.414Z"
  },
  {
    "id": "vlc-29",
    "name": "Gestoría Administrativa Benlliure",
    "legalName": "Gestoría Administrativa Benlliure S.L.P.",
    "industry": "Asesoría Contable & Fiscal",
    "contactName": "Dirección / Titular",
    "contactRole": "Socio Gestor",
    "email": "contacto@gestoraadminist.es",
    "phone": "+34 963 71 95 62",
    "status": "lead",
    "estimatedValue": 0,
    "territory": "espana",
    "assignedTo": "Stefi Del Papa",
    "techRequirements": "Desarrollo de landing page/sitio web moderno optimizado para móviles, optimización SEO local en Valencia (Cabanyal/Marítim) y botón directo de atención WhatsApp.",
    "notes": "Dirección: Carrer Josep Benlliure, 62, 46011 València | WhatsApp no registrado inicialmente | Sin sitio web actual (Oportunidad prioritaria de desarrollo) | Prospecto recopilado en relevamiento territorial Valencia 2026.",
    "createdAt": "2026-09-21T03:56:44.425Z",
    "updatedAt": "2026-09-23T03:56:44.414Z"
  },
  {
    "id": "vlc-30",
    "name": "M. Soler Assessors & Consultors",
    "legalName": "M. Soler Assessors & Consultors S.L.",
    "industry": "Asesoría Contable & Fiscal",
    "contactName": "M. Soler",
    "contactRole": "Titular / Decisor Principal",
    "email": "contacto@msolerassessors.com",
    "phone": "+34 963 55 64 30",
    "website": "https://msolerassessors.com",
    "status": "lead",
    "estimatedValue": 0,
    "territory": "espana",
    "assignedTo": "Stefi Del Papa",
    "techRequirements": "Plataforma segura de consulta documental, portal de cliente para subida de facturas/expedientes y automatización de respuestas frecuentes.",
    "notes": "Dirección: Carrer del Progrés, 102, 46011 València | WhatsApp disponible: +34 650 92 11 47 | Sitio web existente: https://msolerassessors.com | Facebook: msolerassessors | Prospecto recopilado en relevamiento territorial Valencia 2026.",
    "createdAt": "2026-09-22T03:56:44.425Z",
    "updatedAt": "2026-09-23T03:56:44.414Z"
  },
  {
    "id": "vlc-31",
    "name": "Cabanyal Consulting Fiscal & Legal",
    "legalName": "Cabanyal Consulting Fiscal & Legal S.L.",
    "industry": "Servicios Jurídicos & Legal",
    "contactName": "Dirección / Titular",
    "contactRole": "Socio Director",
    "email": "contacto@cabanyalconsult.es",
    "phone": "+34 963 71 28 00",
    "status": "lead",
    "estimatedValue": 0,
    "territory": "espana",
    "assignedTo": "Lic. Mateo Rossi",
    "techRequirements": "Desarrollo de landing page/sitio web moderno optimizado para móviles, optimización SEO local en Valencia (Cabanyal/Marítim) y botón directo de atención WhatsApp.",
    "notes": "Dirección: Carrer d'Ample, 19, 46011 València | WhatsApp no registrado inicialmente | Sin sitio web actual (Oportunidad prioritaria de desarrollo) | Prospecto recopilado en relevamiento territorial Valencia 2026.",
    "createdAt": "2026-09-23T03:56:44.425Z",
    "updatedAt": "2026-09-23T03:56:44.414Z"
  }
];

export const initialValenciaIssues = [
  {
    "id": "iss-vlc-1",
    "issueKey": "IAT-201",
    "title": "Prospección & Portfolio Digital: OSB Arquitectos",
    "description": "Estudio técnico en Valencia. Relevar modernización de portfolio visual en alta resolución y cotizador de proyectos. Contacto: Dirección de Estudio OSB (Arquitecto Titular). Teléfono: +34 963 20 40 85. Email: contacto@osbarquitectos.com.",
    "type": "task",
    "status": "todo",
    "priority": "highest",
    "companyId": "vlc-1",
    "assignedTo": "Lic. Mateo Rossi",
    "storyPoints": 5,
    "value": 0,
    "territory": "espana",
    "dueDate": "2026-09-27T11:36:11.694Z",
    "tags": "[\"Valencia\",\"Arquitectura\",\"Prospección\"]",
    "createdAt": "2026-08-24T03:56:44.423Z",
    "updatedAt": "2026-09-23T11:36:11.681Z"
  },
  {
    "id": "iss-vlc-2",
    "issueKey": "IAT-202",
    "title": "Prospección & Portfolio Digital: Fandiño Arquitectura",
    "description": "Estudio técnico en Valencia. Relevar modernización de portfolio visual en alta resolución y cotizador de proyectos. Contacto: Arq. Carlos Fandiño (Arquitecto Titular). Teléfono: +34 963 71 89 20. Email: contacto@fandinoarquitectura.es.",
    "type": "task",
    "status": "todo",
    "priority": "medium",
    "companyId": "vlc-2",
    "assignedTo": "Stefi Del Papa",
    "storyPoints": 3,
    "value": 0,
    "territory": "espana",
    "dueDate": "2026-09-28T11:36:11.694Z",
    "tags": "[\"Valencia\",\"Arquitectura\",\"Prospección\"]",
    "createdAt": "2026-08-25T03:56:44.424Z",
    "updatedAt": "2026-09-23T11:36:11.681Z"
  },
  {
    "id": "iss-vlc-3",
    "issueKey": "IAT-203",
    "title": "Prospección & Diagnóstico Web: Estudio Arquitectura Cabanyal (Vicente R.)",
    "description": "Comercio/profesional sin sitio web en Dirección: Carrer del Progrés, 88, 46011 València. Elaborar propuesta de landing page moderna, ficha Google Maps y botón de contacto WhatsApp directo. Contacto: Vicente R. (Arquitecto Titular). Teléfono: +34 963 56 12 40. Email: contacto@estudioarquitec.es.",
    "type": "task",
    "status": "todo",
    "priority": "high",
    "companyId": "vlc-3",
    "assignedTo": "Stefi Del Papa",
    "storyPoints": 3,
    "value": 0,
    "territory": "espana",
    "dueDate": "2026-09-29T11:36:11.694Z",
    "tags": "[\"Valencia\",\"Arquitectura\",\"Prospección\"]",
    "createdAt": "2026-08-26T03:56:44.424Z",
    "updatedAt": "2026-09-23T11:36:11.681Z"
  },
  {
    "id": "iss-vlc-4",
    "issueKey": "IAT-204",
    "title": "Prospección & Diagnóstico Web: Reforma y Arquitectura Marítim",
    "description": "Comercio/profesional sin sitio web en Dirección: Carrer d'Ernest Anastasio, 24, 46011 València. Elaborar propuesta de landing page moderna, ficha Google Maps y botón de contacto WhatsApp directo. Contacto: Dirección / Titular (Arquitecto Titular). Teléfono: +34 644 19 82 05. Email: contacto@reformayarquite.es.",
    "type": "task",
    "status": "todo",
    "priority": "medium",
    "companyId": "vlc-4",
    "assignedTo": "Lic. Mateo Rossi",
    "storyPoints": 5,
    "value": 0,
    "territory": "espana",
    "dueDate": "2026-09-30T11:36:11.694Z",
    "tags": "[\"Valencia\",\"Arquitectura\",\"Prospección\"]",
    "createdAt": "2026-08-27T03:56:44.424Z",
    "updatedAt": "2026-09-23T11:36:11.681Z"
  },
  {
    "id": "iss-vlc-5",
    "issueKey": "IAT-205",
    "title": "Prospección & Diagnóstico Web: Arquitectura Técnica & Peritajes Marítim",
    "description": "Comercio/profesional sin sitio web en Dirección: Carrer de la Barraca, 76, 46011 València. Elaborar propuesta de landing page moderna, ficha Google Maps y botón de contacto WhatsApp directo. Contacto: Dirección / Titular (Arquitecto Titular). Teléfono: +34 963 55 41 12. Email: contacto@arquitecturatcn.es.",
    "type": "task",
    "status": "todo",
    "priority": "highest",
    "companyId": "vlc-5",
    "assignedTo": "Stefi Del Papa",
    "storyPoints": 3,
    "value": 0,
    "territory": "espana",
    "dueDate": "2026-10-01T11:36:11.694Z",
    "tags": "[\"Valencia\",\"Arquitectura\",\"Prospección\"]",
    "createdAt": "2026-08-28T03:56:44.424Z",
    "updatedAt": "2026-09-23T11:36:11.681Z"
  },
  {
    "id": "iss-vlc-6",
    "issueKey": "IAT-206",
    "title": "Prospección & Diagnóstico Web: Taller d'Arquitectura El Grau - Cabanyal",
    "description": "Comercio/profesional sin sitio web en Dirección: Carrer Josep Benlliure, 142, 46011 València. Elaborar propuesta de landing page moderna, ficha Google Maps y botón de contacto WhatsApp directo. Contacto: Dirección / Titular (Arquitecto Titular). Teléfono: +34 963 67 30 19. Email: contacto@tallerdarquitec.es.",
    "type": "task",
    "status": "todo",
    "priority": "medium",
    "companyId": "vlc-6",
    "assignedTo": "Stefi Del Papa",
    "storyPoints": 3,
    "value": 0,
    "territory": "espana",
    "dueDate": "2026-10-02T11:36:11.694Z",
    "tags": "[\"Valencia\",\"Arquitectura\",\"Prospección\"]",
    "createdAt": "2026-08-29T03:56:44.424Z",
    "updatedAt": "2026-09-23T11:36:11.681Z"
  },
  {
    "id": "iss-vlc-7",
    "issueKey": "IAT-207",
    "title": "Prospección & Diagnóstico Web: Clínica Dental Dr. Lluch",
    "description": "Comercio/profesional sin sitio web en Dirección: Carrer del Doctor Lluch, 21, 46011 València. Elaborar propuesta de landing page moderna, ficha Google Maps y botón de contacto WhatsApp directo. Contacto: Dr. Lluch (Director Médico). Teléfono: +34 963 71 52 33. Email: contacto@clnicadentaldrl.es.",
    "type": "task",
    "status": "todo",
    "priority": "high",
    "companyId": "vlc-7",
    "assignedTo": "Lic. Mateo Rossi",
    "storyPoints": 5,
    "value": 0,
    "territory": "espana",
    "dueDate": "2026-10-03T11:36:11.695Z",
    "tags": "[\"Valencia\",\"Salud\",\"Prospección\"]",
    "createdAt": "2026-08-30T03:56:44.424Z",
    "updatedAt": "2026-09-23T11:36:11.681Z"
  },
  {
    "id": "iss-vlc-8",
    "issueKey": "IAT-208",
    "title": "Prospección & Turnero WhatsApp: Lainez Dental",
    "description": "Clínica/centro con web activa pero sin automatización de citas. Relevar viabilidad de bot conversacional WhatsApp y sincronización con calendario de consultas. Contacto: Dra. María Láinez (Director Médico). Teléfono: +34 963 22 75 14. Email: contacto@lainezdental.com.",
    "type": "automation",
    "status": "todo",
    "priority": "medium",
    "companyId": "vlc-8",
    "assignedTo": "Stefi Del Papa",
    "storyPoints": 3,
    "value": 0,
    "territory": "espana",
    "dueDate": "2026-10-04T11:36:11.695Z",
    "tags": "[\"Valencia\",\"Salud\",\"Prospección\"]",
    "createdAt": "2026-08-31T03:56:44.424Z",
    "updatedAt": "2026-09-23T11:36:11.681Z"
  },
  {
    "id": "iss-vlc-9",
    "issueKey": "IAT-209",
    "title": "Prospección & Turnero WhatsApp: Clínica Dental Dr. Vicente Faus",
    "description": "Clínica/centro con web activa pero sin automatización de citas. Relevar viabilidad de bot conversacional WhatsApp y sincronización con calendario de consultas. Contacto: Dr. Vicente Faus (Director Médico). Teléfono: +34 960 45 40 20. Email: contacto@drvicentefausdentista.com.",
    "type": "automation",
    "status": "todo",
    "priority": "highest",
    "companyId": "vlc-9",
    "assignedTo": "Stefi Del Papa",
    "storyPoints": 3,
    "value": 0,
    "territory": "espana",
    "dueDate": "2026-10-05T11:36:11.695Z",
    "tags": "[\"Valencia\",\"Salud\",\"Prospección\"]",
    "createdAt": "2026-09-01T03:56:44.424Z",
    "updatedAt": "2026-09-23T11:36:11.681Z"
  },
  {
    "id": "iss-vlc-10",
    "issueKey": "IAT-210",
    "title": "Prospección & Diagnóstico Web: Clínica Dental Cabanyal",
    "description": "Comercio/profesional sin sitio web en Dirección: Carrer de la Reina, 112, 46011 València. Elaborar propuesta de landing page moderna, ficha Google Maps y botón de contacto WhatsApp directo. Contacto: Dirección / Titular (Director Médico). Teléfono: +34 963 71 44 80. Email: contacto@clnicadentalcab.es.",
    "type": "task",
    "status": "todo",
    "priority": "medium",
    "companyId": "vlc-10",
    "assignedTo": "Lic. Mateo Rossi",
    "storyPoints": 5,
    "value": 0,
    "territory": "espana",
    "dueDate": "2026-10-06T11:36:11.695Z",
    "tags": "[\"Valencia\",\"Salud\",\"Prospección\"]",
    "createdAt": "2026-09-02T03:56:44.424Z",
    "updatedAt": "2026-09-23T11:36:11.681Z"
  },
  {
    "id": "iss-vlc-11",
    "issueKey": "IAT-211",
    "title": "Prospección & Diagnóstico Web: Clínica Dental Dra. Amparo Martí",
    "description": "Comercio/profesional sin sitio web en Dirección: Carrer d'Escalante, 89, 46011 València. Elaborar propuesta de landing page moderna, ficha Google Maps y botón de contacto WhatsApp directo. Contacto: Dra. Amparo Martí (Director Médico). Teléfono: +34 963 72 19 02. Email: contacto@clnicadentaldra.es.",
    "type": "task",
    "status": "todo",
    "priority": "high",
    "companyId": "vlc-11",
    "assignedTo": "Stefi Del Papa",
    "storyPoints": 3,
    "value": 0,
    "territory": "espana",
    "dueDate": "2026-10-07T11:36:11.695Z",
    "tags": "[\"Valencia\",\"Salud\",\"Prospección\"]",
    "createdAt": "2026-09-03T03:56:44.424Z",
    "updatedAt": "2026-09-23T11:36:11.681Z"
  },
  {
    "id": "iss-vlc-12",
    "issueKey": "IAT-212",
    "title": "Prospección & Diagnóstico Web: Dental Marítimo (Dra. Sánchez)",
    "description": "Comercio/profesional sin sitio web en Dirección: Avinguda del Mediterrani, 18, 46011 València. Elaborar propuesta de landing page moderna, ficha Google Maps y botón de contacto WhatsApp directo. Contacto: Dra. Carmen Sánchez (Director Médico). Teléfono: +34 963 55 83 29. Email: contacto@dentalmartimodr.es.",
    "type": "task",
    "status": "todo",
    "priority": "medium",
    "companyId": "vlc-12",
    "assignedTo": "Stefi Del Papa",
    "storyPoints": 3,
    "value": 0,
    "territory": "espana",
    "dueDate": "2026-10-08T11:36:11.695Z",
    "tags": "[\"Valencia\",\"Salud\",\"Prospección\"]",
    "createdAt": "2026-09-04T03:56:44.424Z",
    "updatedAt": "2026-09-23T11:36:11.681Z"
  },
  {
    "id": "iss-vlc-13",
    "issueKey": "IAT-213",
    "title": "Prospección & Turnero WhatsApp: Centro AIRE (Fisioterapia y Podología)",
    "description": "Clínica/centro con web activa pero sin automatización de citas. Relevar viabilidad de bot conversacional WhatsApp y sincronización con calendario de consultas. Contacto: Dirección / Titular (Director Médico). Teléfono: +34 962 49 04 00. Email: contacto@airevalencia.es.",
    "type": "automation",
    "status": "backlog",
    "priority": "highest",
    "companyId": "vlc-13",
    "assignedTo": "Lic. Mateo Rossi",
    "storyPoints": 5,
    "value": 0,
    "territory": "espana",
    "dueDate": "2026-10-09T11:36:11.695Z",
    "tags": "[\"Valencia\",\"Salud\",\"Prospección\"]",
    "createdAt": "2026-09-05T03:56:44.424Z",
    "updatedAt": "2026-09-23T11:36:11.681Z"
  },
  {
    "id": "iss-vlc-14",
    "issueKey": "IAT-214",
    "title": "Prospección & Diagnóstico Web: Fisioterapia Marítimo Cabanyal",
    "description": "Comercio/profesional sin sitio web en Dirección: Carrer d'Ernest Anastasio, 15, 46011 València. Elaborar propuesta de landing page moderna, ficha Google Maps y botón de contacto WhatsApp directo. Contacto: Dirección / Titular (Director Médico). Teléfono: +34 963 56 70 88. Email: contacto@fisioterapiamar.es.",
    "type": "task",
    "status": "backlog",
    "priority": "medium",
    "companyId": "vlc-14",
    "assignedTo": "Stefi Del Papa",
    "storyPoints": 3,
    "value": 0,
    "territory": "espana",
    "dueDate": "2026-10-10T11:36:11.695Z",
    "tags": "[\"Valencia\",\"Fisioterapia\",\"Prospección\"]",
    "createdAt": "2026-09-06T03:56:44.425Z",
    "updatedAt": "2026-09-23T11:36:11.681Z"
  },
  {
    "id": "iss-vlc-15",
    "issueKey": "IAT-215",
    "title": "Prospección & Diagnóstico Web: Clínica Podológica Cabanyal",
    "description": "Comercio/profesional sin sitio web en Dirección: Carrer de la Barraca, 54, 46011 València. Elaborar propuesta de landing page moderna, ficha Google Maps y botón de contacto WhatsApp directo. Contacto: Dirección / Titular (Director Médico). Teléfono: +34 963 71 63 94. Email: contacto@clnicapodolgica.es.",
    "type": "task",
    "status": "backlog",
    "priority": "high",
    "companyId": "vlc-15",
    "assignedTo": "Stefi Del Papa",
    "storyPoints": 3,
    "value": 0,
    "territory": "espana",
    "dueDate": "2026-09-27T11:36:11.695Z",
    "tags": "[\"Valencia\",\"Fisioterapia\",\"Prospección\"]",
    "createdAt": "2026-09-07T03:56:44.425Z",
    "updatedAt": "2026-09-23T11:36:11.681Z"
  },
  {
    "id": "iss-vlc-16",
    "issueKey": "IAT-216",
    "title": "Prospección & Diagnóstico Web: Consultorio Médico y Psicológico Cabanyal",
    "description": "Comercio/profesional sin sitio web en Dirección: Carrer de la Reina, 144, 46011 València. Elaborar propuesta de landing page moderna, ficha Google Maps y botón de contacto WhatsApp directo. Contacto: Dirección / Titular (Director Médico). Teléfono: +34 963 55 90 12. Email: contacto@consultoriomdic.es.",
    "type": "task",
    "status": "backlog",
    "priority": "medium",
    "companyId": "vlc-16",
    "assignedTo": "Lic. Mateo Rossi",
    "storyPoints": 5,
    "value": 0,
    "territory": "espana",
    "dueDate": "2026-09-28T11:36:11.695Z",
    "tags": "[\"Valencia\",\"Salud\",\"Prospección\"]",
    "createdAt": "2026-09-08T03:56:44.425Z",
    "updatedAt": "2026-09-23T11:36:11.681Z"
  },
  {
    "id": "iss-vlc-17",
    "issueKey": "IAT-217",
    "title": "Prospección & Turnero WhatsApp: Centro de Psicología y Logopedia Marítims",
    "description": "Clínica/centro con web activa pero sin automatización de citas. Relevar viabilidad de bot conversacional WhatsApp y sincronización con calendario de consultas. Contacto: Dirección / Titular (Director Médico). Teléfono: +34 963 56 42 18. Email: contacto@psicologiamaritims.es.",
    "type": "automation",
    "status": "backlog",
    "priority": "highest",
    "companyId": "vlc-17",
    "assignedTo": "Stefi Del Papa",
    "storyPoints": 3,
    "value": 0,
    "territory": "espana",
    "dueDate": "2026-09-29T11:36:11.695Z",
    "tags": "[\"Valencia\",\"Salud\",\"Prospección\"]",
    "createdAt": "2026-09-09T03:56:44.425Z",
    "updatedAt": "2026-09-23T11:36:11.681Z"
  },
  {
    "id": "iss-vlc-18",
    "issueKey": "IAT-218",
    "title": "Prospección & Diagnóstico Web: Fisioterapia & Osteopatía Escalante",
    "description": "Comercio/profesional sin sitio web en Dirección: Carrer d'Escalante, 65, 46011 València. Elaborar propuesta de landing page moderna, ficha Google Maps y botón de contacto WhatsApp directo. Contacto: Dirección / Titular (Director Médico). Teléfono: +34 963 71 82 40. Email: contacto@fisioterapiaost.es.",
    "type": "task",
    "status": "backlog",
    "priority": "medium",
    "companyId": "vlc-18",
    "assignedTo": "Stefi Del Papa",
    "storyPoints": 3,
    "value": 0,
    "territory": "espana",
    "dueDate": "2026-09-30T11:36:11.695Z",
    "tags": "[\"Valencia\",\"Fisioterapia\",\"Prospección\"]",
    "createdAt": "2026-09-10T03:56:44.425Z",
    "updatedAt": "2026-09-23T11:36:11.681Z"
  },
  {
    "id": "iss-vlc-19",
    "issueKey": "IAT-219",
    "title": "Prospección & Portal Seguro: Ángel Toledo Algarra Abogados",
    "description": "Despacho profesional en Valencia. Presentar solución de portal cliente para intercambio documental seguro y recepción clasificada de consultas. Contacto: Lic. Ángel Toledo Algarra (Socio Director). Teléfono: +34 637 73 65 33. Email: contacto@angeltoledo.com.",
    "type": "consulting",
    "status": "backlog",
    "priority": "high",
    "companyId": "vlc-19",
    "assignedTo": "Lic. Mateo Rossi",
    "storyPoints": 5,
    "value": 0,
    "territory": "espana",
    "dueDate": "2026-10-01T11:36:11.695Z",
    "tags": "[\"Valencia\",\"Servicios\",\"Prospección\"]",
    "createdAt": "2026-09-11T03:56:44.425Z",
    "updatedAt": "2026-09-23T11:36:11.681Z"
  },
  {
    "id": "iss-vlc-20",
    "issueKey": "IAT-220",
    "title": "Prospección & Diagnóstico Web: Zabal Fernández Abogados",
    "description": "Comercio/profesional sin sitio web en Dirección: Carrer del Pintor Ferrandis, 31, 46011 València. Elaborar propuesta de landing page moderna, ficha Google Maps y botón de contacto WhatsApp directo. Contacto: Dirección / Titular (Socio Director). Teléfono: +34 963 71 08 55. Email: contacto@zabalfernndezab.es.",
    "type": "task",
    "status": "backlog",
    "priority": "medium",
    "companyId": "vlc-20",
    "assignedTo": "Stefi Del Papa",
    "storyPoints": 3,
    "value": 0,
    "territory": "espana",
    "dueDate": "2026-10-02T11:36:11.695Z",
    "tags": "[\"Valencia\",\"Servicios\",\"Prospección\"]",
    "createdAt": "2026-09-12T03:56:44.425Z",
    "updatedAt": "2026-09-23T11:36:11.681Z"
  },
  {
    "id": "iss-vlc-21",
    "issueKey": "IAT-221",
    "title": "Prospección & Diagnóstico Web: Despacho Jurídico Marítim (G. Esteve)",
    "description": "Comercio/profesional sin sitio web en Dirección: Carrer Josep Benlliure, 98, 46011 València. Elaborar propuesta de landing page moderna, ficha Google Maps y botón de contacto WhatsApp directo. Contacto: Dr. G. Esteve (Socio Director). Teléfono: +34 963 55 19 40. Email: contacto@despachojurdico.es.",
    "type": "task",
    "status": "backlog",
    "priority": "highest",
    "companyId": "vlc-21",
    "assignedTo": "Stefi Del Papa",
    "storyPoints": 3,
    "value": 0,
    "territory": "espana",
    "dueDate": "2026-10-03T11:36:11.695Z",
    "tags": "[\"Valencia\",\"Servicios\",\"Prospección\"]",
    "createdAt": "2026-09-13T03:56:44.425Z",
    "updatedAt": "2026-09-23T11:36:11.681Z"
  },
  {
    "id": "iss-vlc-22",
    "issueKey": "IAT-222",
    "title": "Prospección & Diagnóstico Web: Bufete Cabanyal Legal",
    "description": "Comercio/profesional sin sitio web en Dirección: Carrer de la Barraca, 110, 46011 València. Elaborar propuesta de landing page moderna, ficha Google Maps y botón de contacto WhatsApp directo. Contacto: Dirección / Titular (Socio Director). Teléfono: +34 963 72 66 11. Email: contacto@bufetecabanyall.es.",
    "type": "task",
    "status": "backlog",
    "priority": "medium",
    "companyId": "vlc-22",
    "assignedTo": "Lic. Mateo Rossi",
    "storyPoints": 5,
    "value": 0,
    "territory": "espana",
    "dueDate": "2026-10-04T11:36:11.695Z",
    "tags": "[\"Valencia\",\"Servicios\",\"Prospección\"]",
    "createdAt": "2026-09-14T03:56:44.425Z",
    "updatedAt": "2026-09-23T11:36:11.681Z"
  },
  {
    "id": "iss-vlc-23",
    "issueKey": "IAT-223",
    "title": "Prospección & Portal Seguro: Ortiz & Asociados Abogados",
    "description": "Despacho profesional en Valencia. Presentar solución de portal cliente para intercambio documental seguro y recepción clasificada de consultas. Contacto: Dirección / Titular (Socio Director). Teléfono: +34 963 71 90 04. Email: contacto@ortizabogadoscabanyal.com.",
    "type": "consulting",
    "status": "backlog",
    "priority": "high",
    "companyId": "vlc-23",
    "assignedTo": "Stefi Del Papa",
    "storyPoints": 3,
    "value": 0,
    "territory": "espana",
    "dueDate": "2026-10-05T11:36:11.695Z",
    "tags": "[\"Valencia\",\"Servicios\",\"Prospección\"]",
    "createdAt": "2026-09-15T03:56:44.425Z",
    "updatedAt": "2026-09-23T11:36:11.681Z"
  },
  {
    "id": "iss-vlc-24",
    "issueKey": "IAT-224",
    "title": "Prospección & Diagnóstico Web: Gestoría Cabanyal SLP",
    "description": "Comercio/profesional sin sitio web en Dirección: Carrer de la Reina, 80, bjo, 46011 València. Elaborar propuesta de landing page moderna, ficha Google Maps y botón de contacto WhatsApp directo. Contacto: Dirección / Titular (Socio Gestor). Teléfono: +34 963 71 14 50. Email: contacto@gestoracabanyal.es.",
    "type": "task",
    "status": "backlog",
    "priority": "medium",
    "companyId": "vlc-24",
    "assignedTo": "Stefi Del Papa",
    "storyPoints": 3,
    "value": 0,
    "territory": "espana",
    "dueDate": "2026-10-06T11:36:11.695Z",
    "tags": "[\"Valencia\",\"Asesoría\",\"Prospección\"]",
    "createdAt": "2026-09-16T03:56:44.425Z",
    "updatedAt": "2026-09-23T11:36:11.681Z"
  },
  {
    "id": "iss-vlc-25",
    "issueKey": "IAT-225",
    "title": "Prospección & Portal Seguro: Canyamelar Assessors",
    "description": "Despacho profesional en Valencia. Presentar solución de portal cliente para intercambio documental seguro y recepción clasificada de consultas. Contacto: Dirección / Titular (Socio Gestor). Teléfono: +34 963 71 85 10. Email: contacto@canyamelarassessors.es.",
    "type": "consulting",
    "status": "backlog",
    "priority": "highest",
    "companyId": "vlc-25",
    "assignedTo": "Lic. Mateo Rossi",
    "storyPoints": 5,
    "value": 0,
    "territory": "espana",
    "dueDate": "2026-10-07T11:36:11.695Z",
    "tags": "[\"Valencia\",\"Asesoría\",\"Prospección\"]",
    "createdAt": "2026-09-17T03:56:44.425Z",
    "updatedAt": "2026-09-23T11:36:11.681Z"
  },
  {
    "id": "iss-vlc-26",
    "issueKey": "IAT-226",
    "title": "Prospección & Diagnóstico Web: Gestoría Crespo",
    "description": "Comercio/profesional sin sitio web en Dirección: Carrer de la Reina, 210, 46011 València. Elaborar propuesta de landing page moderna, ficha Google Maps y botón de contacto WhatsApp directo. Contacto: Dirección / Titular (Socio Gestor). Teléfono: +34 963 71 33 08. Email: contacto@gestoracrespo.es.",
    "type": "task",
    "status": "backlog",
    "priority": "medium",
    "companyId": "vlc-26",
    "assignedTo": "Stefi Del Papa",
    "storyPoints": 3,
    "value": 0,
    "territory": "espana",
    "dueDate": "2026-10-08T11:36:11.695Z",
    "tags": "[\"Valencia\",\"Asesoría\",\"Prospección\"]",
    "createdAt": "2026-09-18T03:56:44.425Z",
    "updatedAt": "2026-09-23T11:36:11.681Z"
  },
  {
    "id": "iss-vlc-27",
    "issueKey": "IAT-227",
    "title": "Prospección & Diagnóstico Web: Asesorías Anelia",
    "description": "Comercio/profesional sin sitio web en Dirección: Carrer de Pedro Maza, 14, 46011 València. Elaborar propuesta de landing page moderna, ficha Google Maps y botón de contacto WhatsApp directo. Contacto: Dirección / Titular (Socio Gestor). Teléfono: +34 963 56 31 75. Email: contacto@asesorasanelia.es.",
    "type": "task",
    "status": "backlog",
    "priority": "high",
    "companyId": "vlc-27",
    "assignedTo": "Stefi Del Papa",
    "storyPoints": 3,
    "value": 0,
    "territory": "espana",
    "dueDate": "2026-10-09T11:36:11.695Z",
    "tags": "[\"Valencia\",\"Asesoría\",\"Prospección\"]",
    "createdAt": "2026-09-19T03:56:44.425Z",
    "updatedAt": "2026-09-23T11:36:11.681Z"
  },
  {
    "id": "iss-vlc-28",
    "issueKey": "IAT-228",
    "title": "Prospección & Diagnóstico Web: Asesoría Fiscal & Laboral Marítimo",
    "description": "Comercio/profesional sin sitio web en Dirección: Carrer de la Reina, 45, 46011 València. Elaborar propuesta de landing page moderna, ficha Google Maps y botón de contacto WhatsApp directo. Contacto: Dirección / Titular (Socio Gestor). Teléfono: +34 963 72 05 91. Email: contacto@asesorafiscalla.es.",
    "type": "task",
    "status": "backlog",
    "priority": "medium",
    "companyId": "vlc-28",
    "assignedTo": "Lic. Mateo Rossi",
    "storyPoints": 5,
    "value": 0,
    "territory": "espana",
    "dueDate": "2026-10-10T11:36:11.695Z",
    "tags": "[\"Valencia\",\"Asesoría\",\"Prospección\"]",
    "createdAt": "2026-09-20T03:56:44.425Z",
    "updatedAt": "2026-09-23T11:36:11.681Z"
  },
  {
    "id": "iss-vlc-29",
    "issueKey": "IAT-229",
    "title": "Prospección & Diagnóstico Web: Gestoría Administrativa Benlliure",
    "description": "Comercio/profesional sin sitio web en Dirección: Carrer Josep Benlliure, 62, 46011 València. Elaborar propuesta de landing page moderna, ficha Google Maps y botón de contacto WhatsApp directo. Contacto: Dirección / Titular (Socio Gestor). Teléfono: +34 963 71 95 62. Email: contacto@gestoraadminist.es.",
    "type": "task",
    "status": "backlog",
    "priority": "highest",
    "companyId": "vlc-29",
    "assignedTo": "Stefi Del Papa",
    "storyPoints": 3,
    "value": 0,
    "territory": "espana",
    "dueDate": "2026-09-27T11:36:11.695Z",
    "tags": "[\"Valencia\",\"Asesoría\",\"Prospección\"]",
    "createdAt": "2026-09-21T03:56:44.425Z",
    "updatedAt": "2026-09-23T11:36:11.681Z"
  },
  {
    "id": "iss-vlc-30",
    "issueKey": "IAT-230",
    "title": "Prospección & Portal Seguro: M. Soler Assessors & Consultors",
    "description": "Despacho profesional en Valencia. Presentar solución de portal cliente para intercambio documental seguro y recepción clasificada de consultas. Contacto: M. Soler (Titular / Decisor Principal). Teléfono: +34 963 55 64 30. Email: contacto@msolerassessors.com.",
    "type": "consulting",
    "status": "backlog",
    "priority": "medium",
    "companyId": "vlc-30",
    "assignedTo": "Stefi Del Papa",
    "storyPoints": 3,
    "value": 0,
    "territory": "espana",
    "dueDate": "2026-09-28T11:36:11.695Z",
    "tags": "[\"Valencia\",\"Asesoría\",\"Prospección\"]",
    "createdAt": "2026-09-22T03:56:44.425Z",
    "updatedAt": "2026-09-23T11:36:11.681Z"
  },
  {
    "id": "iss-vlc-31",
    "issueKey": "IAT-231",
    "title": "Prospección & Diagnóstico Web: Cabanyal Consulting Fiscal & Legal",
    "description": "Comercio/profesional sin sitio web en Dirección: Carrer d'Ample, 19, 46011 València. Elaborar propuesta de landing page moderna, ficha Google Maps y botón de contacto WhatsApp directo. Contacto: Dirección / Titular (Socio Director). Teléfono: +34 963 71 28 00. Email: contacto@cabanyalconsult.es.",
    "type": "task",
    "status": "backlog",
    "priority": "high",
    "companyId": "vlc-31",
    "assignedTo": "Lic. Mateo Rossi",
    "storyPoints": 5,
    "value": 0,
    "territory": "espana",
    "dueDate": "2026-09-29T11:36:11.695Z",
    "tags": "[\"Valencia\",\"Servicios\",\"Prospección\"]",
    "createdAt": "2026-09-23T03:56:44.425Z",
    "updatedAt": "2026-09-23T11:36:11.681Z"
  }
];

export const initialValenciaActivities = [
  {
    "id": "act-vlc-1",
    "companyId": "vlc-1",
    "type": "note",
    "summary": "Relevamiento territorial de estudio de arquitectura",
    "details": "Estudio de arquitectura consolidado en Carrer Escalante con sitio web activo. Oportunidad en optimización de portfolio y automatización de recepción de briefs.",
    "author": "Stefi Del Papa",
    "nextAction": "Preparar diagnóstico web personalizado",
    "nextActionDate": "2026-09-26T03:56:44.425Z",
    "createdAt": "2026-09-21T03:56:44.425Z"
  },
  {
    "id": "act-vlc-2",
    "companyId": "vlc-8",
    "type": "note",
    "summary": "Identificación de requerimientos de agendamiento online",
    "details": "Clínica dental con alta concurrencia en Serrería. Cuentan con WhatsApp pero sin turnero automático integrado a su sitio web.",
    "author": "Stefi Del Papa",
    "nextAction": "Contacto con Dra. Láinez para presentación breve",
    "nextActionDate": "2026-09-27T03:56:44.425Z",
    "createdAt": "2026-09-22T03:56:44.425Z"
  },
  {
    "id": "act-vlc-3",
    "companyId": "vlc-13",
    "type": "note",
    "summary": "Ficha de contacto y servicios en Centro AIRE",
    "details": "Centro multidisciplinar de fisioterapia y podología. Tienen web propia y actividad en redes. Excelente prospecto para canal de reservas 24/7.",
    "author": "Lic. Mateo Rossi",
    "nextAction": "Revisión conjunta con Stefi de propuesta de bot WhatsApp",
    "nextActionDate": "2026-09-25T03:56:44.425Z",
    "createdAt": "2026-09-23T03:56:44.414Z"
  }
];

export const initialWebInquiries = [
  {
    id: "lead-inb-001",
    name: "Dr. Marcos Benítez",
    email: "marcos.benitez@clinicasalud.es",
    company: "Clínica Benítez & Asociados",
    phone: "+34 611 45 88 90",
    service: "Desarrollo de Herramientas IA",
    message: "Hola, vimos su video explicativo de servicios. Nos interesa implementar un asistente de IA para triaje y agendamiento automático de pacientes en WhatsApp integrado con nuestro sistema.",
    status: "nuevo",
    assignedTo: "Lic. Mateo Rossi",
    createdAt: new Date(Date.now() - 3600000 * 3).toISOString()
  },
  {
    id: "lead-inb-002",
    name: "Valeria Santillán",
    email: "valeria@innovalogistica.com",
    company: "Innova Logística Express",
    phone: "+54 9 11 4820-9912",
    service: "Software a Medida & Apps",
    message: "Quisiéramos coordinar una demo para evaluar el desarrollo de una app de seguimiento de despachos y panel de control web para nuestros clientes corporativos.",
    status: "nuevo",
    assignedTo: "Lic. Mateo Rossi",
    createdAt: new Date(Date.now() - 3600000 * 22).toISOString()
  },
  {
    id: "lead-inb-003",
    name: "Tomás Albarracín",
    email: "tomas@patagoniaecotours.com.ar",
    company: "Patagonia Eco Tours",
    phone: "+54 9 294 456-1122",
    service: "Consultoría & Asesoramiento",
    message: "Buscamos una consultoría integral para renovar nuestra plataforma digital y automatizar las reservas de expediciones turísticas en Bariloche.",
    status: "en_contacto",
    assignedTo: "José Anaya",
    createdAt: new Date(Date.now() - 3600000 * 48).toISOString()
  }
];

